import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { VitePWA } from "vite-plugin-pwa";
import type { PluginOption } from "vite";
import packageJson from "./package.json";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  server: {
    // Giới hạn chỉ lắng nghe localhost và tắt CORS để tránh trang web khác đọc nội dung dev server
    host: "127.0.0.1",
    port: 3000,
    cors: false,
  },
  preview: {
    host: "127.0.0.1",
    port: 4173,
    cors: false,
  },
  define: {
    __APP_VERSION__: JSON.stringify(packageJson.version),
  },
  esbuild: {
    target: 'esnext',
  },
  optimizeDeps: {
    exclude: ['chunk-SFLVWKAX', 'chunk-YV7AFGPB'],
    esbuildOptions: {
      target: 'esnext',
    },
  },
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.ico', 'apple-touch-icon-180x180.png', 'robots.txt', 'og-image.png', 'tingting-link-preview.png'],
      manifest: {
        // Stable app identity — survives start_url changes so an installed app
        // doesn't fragment into a duplicate home-screen entry.
        id: '/',
        name: 'Ting Ting',
        short_name: 'Ting Ting',
        description: 'Nền tảng quản lý nhân sự, chấm công, ứng lương và thanh toán lương cho doanh nghiệp xây dựng.',
        theme_color: '#000000',
        background_color: '#000000',
        display: 'standalone',
        orientation: 'portrait-primary',
        // Icons generated by `yarn pwa:generate` (@vite-pwa/assets-generator).
        // 192/512 satisfy Android/Chrome installability; the maskable variant
        // adapts to Android icon shapes; the 180 apple-touch-icon is wired in
        // index.html. vite-plugin-pwa auto-precaches these manifest icons.
        icons: [
          { src: '/pwa-64x64.png', sizes: '64x64', type: 'image/png' },
          { src: '/pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: '/pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          {
            src: '/maskable-icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      injectManifest: {
        maximumFileSizeToCacheInBytes: 3 * 1024 * 1024, // 3 MB for pdfMake
      },
      // Enable the service worker in `vite dev` so push notifications can
      // be tested locally. Without this, sw.ts is only emitted by the
      // production build and `navigator.serviceWorker.ready` hangs forever.
      devOptions: {
        enabled: true,
        type: 'module',
        navigateFallback: 'index.html',
      }
    }) as PluginOption
  ].filter(Boolean),
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  build: {
    target: 'esnext',
    rollupOptions: {
      output: {
        // Enable filename hashing for cache busting
        entryFileNames: `assets/[name].[hash].js`,
        chunkFileNames: `assets/[name].[hash].js`,
        assetFileNames: `assets/[name].[hash].[ext]`,
        // Object-form manualChunks misses CommonJS-wrapped modules (react,
        // react-dom): it emitted an empty "vendor" chunk while react-dom merged
        // into ui. Match module paths instead — this also survives pnpm's
        // .pnpm/ directory layout and package subpaths like react/jsx-runtime.
        manualChunks(id) {
          if (!id.includes('node_modules')) return undefined;
          if (/[\\/]node_modules[\\/](react|react-dom)[\\/]/.test(id)) return 'vendor';
          if (/[\\/]node_modules[\\/]@radix-ui[\\/]react-(dialog|dropdown-menu|select)[\\/]/.test(id)) return 'ui';
          if (/[\\/]node_modules[\\/]lucide-react[\\/]/.test(id)) return 'icons';
          if (/[\\/]node_modules[\\/](axios|@tanstack[\\/]react-query)[\\/]/.test(id)) return 'utils';
          if (/[\\/]node_modules[\\/](chart\.js|recharts)[\\/]/.test(id)) return 'charts';
          // cspell:disable-next-line
          if (/[\\/]node_modules[\\/]pdfmake[\\/]/.test(id)) return 'pdfmake';
          return undefined;
        },
      },
    },
    // Warn only when a chunk would exceed the SW precache budget
    // (maximumFileSizeToCacheInBytes above): past that size a file silently
    // drops out of precaching. pdfmake (engine + fonts) is ~2.2 MB by design
    // and lazy-loaded; splitting the 1.5 MB entry chunk is a separate
    // route-level follow-up.
    chunkSizeWarningLimit: 3072,
    // Generate source maps for better debugging
    sourcemap: mode !== 'production',
  },
}));
