package domain

import (
	"fmt"
	"strings"
)

// AuditMatrix provides clean Vietnamese audit message templates keyed by (AuditAction, EntityType).
// Templates include the actor as the first parameter and produce complete, ready-to-use sentences.
var AuditMatrix = map[AuditAction]map[EntityType]string{
	AuditActionCreate: {
		EntityTypeUser:            "%s đã tạo người dùng %s",
		EntityTypeEmployee:        "%s đã tạo hồ sơ nhân viên %s",
		EntityTypeProject:         "%s đã tạo dự án %s",
		EntityTypeProjectEmployee: "%s đã phân công %s vào dự án %s với vai trò %s",
		EntityTypeProjectUser:     "%s đã chia sẻ dự án %s với người dùng %s",
		EntityTypeEmployeeUser:    "%s đã cấp quyền truy cập cho %s vào dự án %s với vai trò %s",
		EntityTypeTimesheet:       "%s đã tạo bảng công cho %s trong dự án %s",
		// Transactions use a preformatted Vietnamese phrase as the second argument
		// (e.g. "doanh thu 45.000 ₫") generated by encodeTransactionEntityName.
		EntityTypeTransaction:               "%s tạo %s",
		EntityTypeLoan:                      "%s đã tạo khoản vay với %s số tiền %s VND",
		EntityTypeLedgerEntry:               "%s đã tạo bút toán cho tài khoản %s số tiền %s VND",
		EntityTypeAsset:                     "%s đã tải lên tài liệu %s",
		EntityTypeSettings:                  "%s đã tạo thiết lập %s",
		EntityTypeBank:                      "%s đã thêm ngân hàng %s",
		EntityTypeLender:                    "%s đã tạo đơn vị cho vay %s",
		EntityTypePayrate:                   "%s đã tạo mức lương cho dự án %s",
		EntityTypeAdvancePaymentFeeSchedule: "%s đã thêm cấu hình phí ứng lương hiệu lực từ %s (%s)",
		EntityTypeDisbursementFeeSchedule:   "%s đã thêm cấu hình phí giao dịch chi hộ hiệu lực từ %s (%s VND)",
	},
	AuditActionUpdate: {
		EntityTypeUser:                      "%s đã cập nhật thông tin người dùng %s",
		EntityTypeEmployee:                  "%s đã cập nhật hồ sơ nhân viên %s",
		EntityTypeProject:                   "%s đã cập nhật dự án %s",
		EntityTypeProjectEmployee:           "%s đã cập nhật phân công của nhân viên %s trong dự án %s",
		EntityTypeProjectUser:               "%s đã cập nhật chia sẻ dự án %s với %s",
		EntityTypeEmployeeUser:              "%s đã cập nhật quyền truy cập nhân viên %s trong dự án %s với vai trò %s",
		EntityTypeTimesheet:                 "%s đã cập nhật bảng công của nhân viên %s trong dự án %s",
		EntityTypeTransaction:               "%s cập nhật %s",
		EntityTypeLoan:                      "%s đã cập nhật khoản vay với %s",
		EntityTypeLedgerEntry:               "%s đã cập nhật bút toán %s",
		EntityTypeAsset:                     "%s đã cập nhật tài liệu %s",
		EntityTypeSettings:                  "%s đã cập nhật thiết lập %s",
		EntityTypeBank:                      "%s đã cập nhật ngân hàng %s",
		EntityTypeLender:                    "%s đã cập nhật đơn vị cho vay %s",
		EntityTypePayrate:                   "%s đã cập nhật mức lương cho dự án %s",
		EntityTypeAdvancePaymentFeeSchedule: "%s đã cập nhật cấu hình phí ứng lương hiệu lực từ %s (%s)",
		EntityTypeDisbursementFeeSchedule:   "%s đã cập nhật cấu hình phí giao dịch chi hộ hiệu lực từ %s (%s VND)",
	},
	AuditActionDelete: {
		EntityTypeUser:                      "%s đã xóa người dùng %s",
		EntityTypeEmployee:                  "%s đã xóa hồ sơ nhân viên %s",
		EntityTypeProject:                   "%s đã xóa dự án %s",
		EntityTypeProjectEmployee:           "%s đã xóa phân công nhân viên %s khỏi dự án %s",
		EntityTypeProjectUser:               "%s đã hủy chia sẻ dự án %s với người dùng %s",
		EntityTypeEmployeeUser:              "%s đã thu hồi quyền truy cập của %s khỏi dự án %s",
		EntityTypeTimesheet:                 "%s đã xóa bảng công của nhân viên %s trong dự án %s",
		EntityTypeTransaction:               "%s xóa %s",
		EntityTypeLoan:                      "%s đã xóa khoản vay với %s",
		EntityTypeLedgerEntry:               "%s đã xóa bút toán %s",
		EntityTypeAsset:                     "%s đã xóa tài liệu %s",
		EntityTypeSettings:                  "%s đã xóa thiết lập %s",
		EntityTypeBank:                      "%s đã xóa ngân hàng %s",
		EntityTypeLender:                    "%s đã xóa đơn vị cho vay %s",
		EntityTypePayrate:                   "%s đã xóa mức lương cho dự án %s",
		EntityTypeAdvancePaymentFeeSchedule: "%s đã xóa cấu hình phí ứng lương hiệu lực từ %s (%s)",
		EntityTypeDisbursementFeeSchedule:   "%s đã xóa cấu hình phí giao dịch chi hộ hiệu lực từ %s (%s VND)",
	},
	AuditActionApprove: {
		EntityTypeTimesheet: "%s đã duyệt bảng công của nhân viên %s trong dự án %s",
		EntityTypeLoan:      "%s đã duyệt khoản vay với %s",
	},
	AuditActionReject: {
		EntityTypeTimesheet: "%s đã từ chối bảng công của nhân viên %s trong dự án %s",
		EntityTypeLoan:      "%s đã từ chối khoản vay của %s",
	},
	AuditActionSettle: {
		EntityTypeTransaction: "%s đã tất toán giao dịch số tiền %s VND",
	},
	AuditActionBulkApprove: {
		EntityTypeTimesheet: "%s đã duyệt %d bảng công trong dự án %s",
	},
	AuditActionBulkReject: {
		EntityTypeTimesheet: "%s đã từ chối %d bảng công trong dự án %s",
	},
	AuditActionBulkReset: {
		EntityTypeTimesheet: "%s đã đặt lại trạng thái của %d bảng công trong dự án %s",
	},
	AuditActionBulkCreate: {
		EntityTypeTimesheet:   "%s đã tạo %d bảng công trong dự án %s",
		EntityTypeTransaction: "%s đã xử lý chuyển khoản hàng loạt từ file %s: %d thành công, %d thất bại",
	},
	AuditActionChangePassword: {
		EntityTypeUser: "%s đã thay đổi mật khẩu cho người dùng %s bằng phương thức %s",
	},
	AuditActionLogin: {
		EntityTypeUser: "%s đã đăng nhập vào hệ thống",
	},
	AuditActionLogout: {
		EntityTypeUser: "%s đã đăng xuất khỏi hệ thống",
	},
	AuditActionExport: {
		EntityTypeBulkTransferFile: "%s đã xuất file chuyển lô %s, tổng giao dịch %s ₫",
	},
	AuditActionImport: {
		EntityTypeBulkTransferFile: "%s nhập file kết quả chuyển lô tạm ứng, tổng giao dịch %s ₫",
	},
	AuditActionView: {
		EntityTypeBulkTransferFile: "%s đã tải lại file chuyển lô %s",
		EntityTypePayroll:          "%s đã xuất lịch sử bảng lương từ %s đến %s",
	},
}

// LookupTemplate finds the appropriate template for a given action and entity type.
// Returns empty string and false if not found.
func LookupTemplate(action AuditAction, entityType EntityType) (string, bool) {
	if entityTypes, ok := AuditMatrix[action]; ok {
		if template, ok := entityTypes[entityType]; ok {
			return template, true
		}
	}
	return "", false
}

// BuildAuditMessageFromMatrix uses the template matrix to build a complete audit message.
// Actor should be the first parameter, followed by context-specific parameters.
func BuildAuditMessageFromMatrix(action AuditAction, entityType EntityType, args ...interface{}) string {
	template, ok := LookupTemplate(action, entityType)
	if !ok {
		return ""
	}
	return fmt.Sprintf(template, args...)
}

// BuildEventAuditMessage builds a complete audit message ready for database insertion.
// Takes action, entity type, actor's full name, and context parameters.
// Returns the final Vietnamese sentence without any placeholders or post-processing.
func BuildEventAuditMessage(action AuditAction, entityType EntityType, actorName string, contextArgs ...interface{}) string {
	template, ok := LookupTemplate(action, entityType)
	if !ok {
		return ""
	}

	// Actor is the first parameter, followed by context-specific parameters
	allArgs := append([]interface{}{actorName}, contextArgs...)
	return fmt.Sprintf(template, allArgs...)
}

// MapRoleToVietnamese converts English role names to Vietnamese
func MapRoleToVietnamese(role string) string {
	roleLower := strings.ToLower(role)
	switch roleLower {
	case "admin":
		return "Quản trị viên"
	case "partner":
		return "Quản lý"
	case "employee":
		return "Nhân viên"
	default:
		return "Người dùng"
	}
}
