CREATE TABLE flexpay_salary_notifications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    asset_id BIGINT UNSIGNED NOT NULL,
    project_id BIGINT UNSIGNED NOT NULL,
    employee_id BIGINT UNSIGNED NOT NULL,
    template_id VARCHAR(32) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    customer_name VARCHAR(30) NOT NULL,
    max_amount BIGINT NOT NULL,
    expiry_date DATE NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    attempt INT UNSIGNED NOT NULL DEFAULT 0,
    lease_expires_at DATETIME NULL,
    enqueued_at DATETIME NULL,
    sent_at DATETIME NULL,
    provider_msg_id VARCHAR(128) NOT NULL DEFAULT '',
    provider_code INT NOT NULL DEFAULT 0,
    last_error VARCHAR(512) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_flexpay_salary_notification_delivery (asset_id, project_id, employee_id, template_id),
    KEY idx_flexpay_salary_notification_recovery (status, lease_expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
