// Code generated by MockGen. DO NOT EDIT.
// Source: api-server/internal/domain (interfaces: ProjectEmployeeRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api-server/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockProjectEmployeeRepository is a mock of ProjectEmployeeRepository interface.
type MockProjectEmployeeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectEmployeeRepositoryMockRecorder
}

// MockProjectEmployeeRepositoryMockRecorder is the mock recorder for MockProjectEmployeeRepository.
type MockProjectEmployeeRepositoryMockRecorder struct {
	mock *MockProjectEmployeeRepository
}

// NewMockProjectEmployeeRepository creates a new mock instance.
func NewMockProjectEmployeeRepository(ctrl *gomock.Controller) *MockProjectEmployeeRepository {
	mock := &MockProjectEmployeeRepository{ctrl: ctrl}
	mock.recorder = &MockProjectEmployeeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectEmployeeRepository) EXPECT() *MockProjectEmployeeRepositoryMockRecorder {
	return m.recorder
}

// ApplyScheduleChanges mocks base method.
func (m *MockProjectEmployeeRepository) ApplyScheduleChanges(arg0 context.Context, arg1 []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyScheduleChanges", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyScheduleChanges indicates an expected call of ApplyScheduleChanges.
func (mr *MockProjectEmployeeRepositoryMockRecorder) ApplyScheduleChanges(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyScheduleChanges", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).ApplyScheduleChanges), arg0, arg1)
}

// BulkUpdateLastDate mocks base method.
func (m *MockProjectEmployeeRepository) BulkUpdateLastDate(arg0 context.Context, arg1 []uint, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateLastDate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateLastDate indicates an expected call of BulkUpdateLastDate.
func (mr *MockProjectEmployeeRepositoryMockRecorder) BulkUpdateLastDate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateLastDate", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).BulkUpdateLastDate), arg0, arg1, arg2)
}

// Count mocks base method.
func (m *MockProjectEmployeeRepository) Count(arg0 context.Context, arg1 domain.ProjectEmployeeFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockProjectEmployeeRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).Count), arg0, arg1)
}

// CountActiveEmployeesByPaymentSchedule mocks base method.
func (m *MockProjectEmployeeRepository) CountActiveEmployeesByPaymentSchedule(arg0 context.Context, arg1 domain.PaymentSchedule) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveEmployeesByPaymentSchedule", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveEmployeesByPaymentSchedule indicates an expected call of CountActiveEmployeesByPaymentSchedule.
func (mr *MockProjectEmployeeRepositoryMockRecorder) CountActiveEmployeesByPaymentSchedule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveEmployeesByPaymentSchedule", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).CountActiveEmployeesByPaymentSchedule), arg0, arg1)
}

// CountWorkingEmployees mocks base method.
func (m *MockProjectEmployeeRepository) CountWorkingEmployees(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountWorkingEmployees", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountWorkingEmployees indicates an expected call of CountWorkingEmployees.
func (mr *MockProjectEmployeeRepositoryMockRecorder) CountWorkingEmployees(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountWorkingEmployees", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).CountWorkingEmployees), arg0)
}

// Create mocks base method.
func (m *MockProjectEmployeeRepository) Create(arg0 context.Context, arg1 *domain.ProjectEmployee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectEmployeeRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockProjectEmployeeRepository) Delete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectEmployeeRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).Delete), arg0, arg1)
}

// DeleteAssignmentsByEmployeeID mocks base method.
func (m *MockProjectEmployeeRepository) DeleteAssignmentsByEmployeeID(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAssignmentsByEmployeeID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAssignmentsByEmployeeID indicates an expected call of DeleteAssignmentsByEmployeeID.
func (mr *MockProjectEmployeeRepositoryMockRecorder) DeleteAssignmentsByEmployeeID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAssignmentsByEmployeeID", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).DeleteAssignmentsByEmployeeID), arg0, arg1)
}

// DeleteByProjectID mocks base method.
func (m *MockProjectEmployeeRepository) DeleteByProjectID(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByProjectID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByProjectID indicates an expected call of DeleteByProjectID.
func (mr *MockProjectEmployeeRepositoryMockRecorder) DeleteByProjectID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByProjectID", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).DeleteByProjectID), arg0, arg1)
}

// EndAssignment mocks base method.
func (m *MockProjectEmployeeRepository) EndAssignment(arg0 context.Context, arg1 uint, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndAssignment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndAssignment indicates an expected call of EndAssignment.
func (mr *MockProjectEmployeeRepositoryMockRecorder) EndAssignment(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndAssignment", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).EndAssignment), arg0, arg1, arg2)
}

// GetActiveAssignmentByProjectAndEmployee mocks base method.
func (m *MockProjectEmployeeRepository) GetActiveAssignmentByProjectAndEmployee(arg0 context.Context, arg1, arg2 uint) (*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveAssignmentByProjectAndEmployee", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveAssignmentByProjectAndEmployee indicates an expected call of GetActiveAssignmentByProjectAndEmployee.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetActiveAssignmentByProjectAndEmployee(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveAssignmentByProjectAndEmployee", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetActiveAssignmentByProjectAndEmployee), arg0, arg1, arg2)
}

// GetActiveAssignments mocks base method.
func (m *MockProjectEmployeeRepository) GetActiveAssignments(arg0 context.Context, arg1 uint) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveAssignments", arg0, arg1)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveAssignments indicates an expected call of GetActiveAssignments.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetActiveAssignments(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveAssignments", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetActiveAssignments), arg0, arg1)
}

// GetActiveAssignmentsByProjectsAndEmployees mocks base method.
func (m *MockProjectEmployeeRepository) GetActiveAssignmentsByProjectsAndEmployees(arg0 context.Context, arg1, arg2 []uint) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveAssignmentsByProjectsAndEmployees", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveAssignmentsByProjectsAndEmployees indicates an expected call of GetActiveAssignmentsByProjectsAndEmployees.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetActiveAssignmentsByProjectsAndEmployees(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveAssignmentsByProjectsAndEmployees", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetActiveAssignmentsByProjectsAndEmployees), arg0, arg1, arg2)
}

// GetActiveEmployeesForProjectWithCreatorFilter mocks base method.
func (m *MockProjectEmployeeRepository) GetActiveEmployeesForProjectWithCreatorFilter(arg0 context.Context, arg1 uint, arg2 *uint) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveEmployeesForProjectWithCreatorFilter", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveEmployeesForProjectWithCreatorFilter indicates an expected call of GetActiveEmployeesForProjectWithCreatorFilter.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetActiveEmployeesForProjectWithCreatorFilter(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveEmployeesForProjectWithCreatorFilter", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetActiveEmployeesForProjectWithCreatorFilter), arg0, arg1, arg2)
}

// GetActiveProjectsForEmployee mocks base method.
func (m *MockProjectEmployeeRepository) GetActiveProjectsForEmployee(arg0 context.Context, arg1 uint) ([]*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveProjectsForEmployee", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveProjectsForEmployee indicates an expected call of GetActiveProjectsForEmployee.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetActiveProjectsForEmployee(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveProjectsForEmployee", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetActiveProjectsForEmployee), arg0, arg1)
}

// GetByEmployee mocks base method.
func (m *MockProjectEmployeeRepository) GetByEmployee(arg0 context.Context, arg1 uint) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmployee", arg0, arg1)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmployee indicates an expected call of GetByEmployee.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetByEmployee(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmployee", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetByEmployee), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockProjectEmployeeRepository) GetByID(arg0 context.Context, arg1 uint) (*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetByID), arg0, arg1)
}

// GetByProject mocks base method.
func (m *MockProjectEmployeeRepository) GetByProject(arg0 context.Context, arg1 uint) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProject", arg0, arg1)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProject indicates an expected call of GetByProject.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetByProject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProject", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetByProject), arg0, arg1)
}

// GetByProjectAndEmployee mocks base method.
func (m *MockProjectEmployeeRepository) GetByProjectAndEmployee(arg0 context.Context, arg1, arg2 uint) (*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectAndEmployee", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectAndEmployee indicates an expected call of GetByProjectAndEmployee.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetByProjectAndEmployee(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectAndEmployee", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetByProjectAndEmployee), arg0, arg1, arg2)
}

// GetCurrentProjectForEmployee mocks base method.
func (m *MockProjectEmployeeRepository) GetCurrentProjectForEmployee(arg0 context.Context, arg1 uint) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentProjectForEmployee", arg0, arg1)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentProjectForEmployee indicates an expected call of GetCurrentProjectForEmployee.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetCurrentProjectForEmployee(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentProjectForEmployee", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetCurrentProjectForEmployee), arg0, arg1)
}

// GetCurrentProjectsForEmployees mocks base method.
func (m *MockProjectEmployeeRepository) GetCurrentProjectsForEmployees(arg0 context.Context, arg1 []uint) (map[uint]*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentProjectsForEmployees", arg0, arg1)
	ret0, _ := ret[0].(map[uint]*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentProjectsForEmployees indicates an expected call of GetCurrentProjectsForEmployees.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetCurrentProjectsForEmployees(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentProjectsForEmployees", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetCurrentProjectsForEmployees), arg0, arg1)
}

// GetEmployeesByPaymentSchedule mocks base method.
func (m *MockProjectEmployeeRepository) GetEmployeesByPaymentSchedule(arg0 context.Context, arg1 domain.PaymentSchedule) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeesByPaymentSchedule", arg0, arg1)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeesByPaymentSchedule indicates an expected call of GetEmployeesByPaymentSchedule.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetEmployeesByPaymentSchedule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeesByPaymentSchedule", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetEmployeesByPaymentSchedule), arg0, arg1)
}

// GetEmployeesWithPendingScheduleChanges mocks base method.
func (m *MockProjectEmployeeRepository) GetEmployeesWithPendingScheduleChanges(arg0 context.Context, arg1 time.Time) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeesWithPendingScheduleChanges", arg0, arg1)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeesWithPendingScheduleChanges indicates an expected call of GetEmployeesWithPendingScheduleChanges.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetEmployeesWithPendingScheduleChanges(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeesWithPendingScheduleChanges", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetEmployeesWithPendingScheduleChanges), arg0, arg1)
}

// GetEmployeesWithPendingCheckInEnable mocks base method.
func (m *MockProjectEmployeeRepository) GetEmployeesWithPendingCheckInEnable(arg0 context.Context, arg1 time.Time) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeesWithPendingCheckInEnable", arg0, arg1)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeesWithPendingCheckInEnable indicates an expected call of GetEmployeesWithPendingCheckInEnable.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetEmployeesWithPendingCheckInEnable(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeesWithPendingCheckInEnable", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetEmployeesWithPendingCheckInEnable), arg0, arg1)
}

// GetOverlappingAssignments mocks base method.
func (m *MockProjectEmployeeRepository) GetOverlappingAssignments(arg0 context.Context, arg1 uint, arg2, arg3 *time.Time) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverlappingAssignments", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverlappingAssignments indicates an expected call of GetOverlappingAssignments.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetOverlappingAssignments(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverlappingAssignments", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetOverlappingAssignments), arg0, arg1, arg2, arg3)
}

// HardDeleteAssignmentsByEmployeeID mocks base method.
func (m *MockProjectEmployeeRepository) HardDeleteAssignmentsByEmployeeID(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDeleteAssignmentsByEmployeeID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDeleteAssignmentsByEmployeeID indicates an expected call of HardDeleteAssignmentsByEmployeeID.
func (mr *MockProjectEmployeeRepositoryMockRecorder) HardDeleteAssignmentsByEmployeeID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDeleteAssignmentsByEmployeeID", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).HardDeleteAssignmentsByEmployeeID), arg0, arg1)
}

// HasAccessViaProject mocks base method.
func (m *MockProjectEmployeeRepository) HasAccessViaProject(arg0 context.Context, arg1, arg2 uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAccessViaProject", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasAccessViaProject indicates an expected call of HasAccessViaProject.
func (mr *MockProjectEmployeeRepositoryMockRecorder) HasAccessViaProject(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAccessViaProject", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).HasAccessViaProject), arg0, arg1, arg2)
}

// HasActiveFlexiblePaymentScheduleByEmployeeID mocks base method.
func (m *MockProjectEmployeeRepository) HasActiveFlexiblePaymentScheduleByEmployeeID(arg0 context.Context, arg1 uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveFlexiblePaymentScheduleByEmployeeID", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasActiveFlexiblePaymentScheduleByEmployeeID indicates an expected call of HasActiveFlexiblePaymentScheduleByEmployeeID.
func (mr *MockProjectEmployeeRepositoryMockRecorder) HasActiveFlexiblePaymentScheduleByEmployeeID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveFlexiblePaymentScheduleByEmployeeID", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).HasActiveFlexiblePaymentScheduleByEmployeeID), arg0, arg1)
}

// List mocks base method.
func (m *MockProjectEmployeeRepository) List(arg0 context.Context, arg1 domain.ProjectEmployeeFilters) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectEmployeeRepositoryMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockProjectEmployeeRepository) Update(arg0 context.Context, arg1 *domain.ProjectEmployee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectEmployeeRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).Update), arg0, arg1)
}

// UpdatePosition mocks base method.
func (m *MockProjectEmployeeRepository) UpdatePosition(arg0 context.Context, arg1 uint, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePosition", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePosition indicates an expected call of UpdatePosition.
func (mr *MockProjectEmployeeRepositoryMockRecorder) UpdatePosition(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePosition", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).UpdatePosition), arg0, arg1, arg2)
}

// UpdatePositionIfCurrent mocks base method.
func (m *MockProjectEmployeeRepository) UpdatePositionIfCurrent(arg0 context.Context, arg1 uint, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePositionIfCurrent", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePositionIfCurrent indicates an expected call of UpdatePositionIfCurrent.
func (mr *MockProjectEmployeeRepositoryMockRecorder) UpdatePositionIfCurrent(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePositionIfCurrent", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).UpdatePositionIfCurrent), arg0, arg1, arg2, arg3)
}
