// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/domain/project_employee.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api-server/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockProjectEmployeeRepository is a mock of ProjectEmployeeRepository interface.
type MockProjectEmployeeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectEmployeeRepositoryMockRecorder
}

// MockProjectEmployeeRepositoryMockRecorder is the mock recorder for MockProjectEmployeeRepository.
type MockProjectEmployeeRepositoryMockRecorder struct {
	mock *MockProjectEmployeeRepository
}

// NewMockProjectEmployeeRepository creates a new mock instance.
func NewMockProjectEmployeeRepository(ctrl *gomock.Controller) *MockProjectEmployeeRepository {
	mock := &MockProjectEmployeeRepository{ctrl: ctrl}
	mock.recorder = &MockProjectEmployeeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectEmployeeRepository) EXPECT() *MockProjectEmployeeRepositoryMockRecorder {
	return m.recorder
}

// ApplyScheduleChanges mocks base method.
func (m *MockProjectEmployeeRepository) ApplyScheduleChanges(ctx context.Context, employeeIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyScheduleChanges", ctx, employeeIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyScheduleChanges indicates an expected call of ApplyScheduleChanges.
func (mr *MockProjectEmployeeRepositoryMockRecorder) ApplyScheduleChanges(ctx, employeeIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyScheduleChanges", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).ApplyScheduleChanges), ctx, employeeIDs)
}

// BulkUpdateLastDate mocks base method.
func (m *MockProjectEmployeeRepository) BulkUpdateLastDate(ctx context.Context, assignmentIDs []uint, lastDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateLastDate", ctx, assignmentIDs, lastDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateLastDate indicates an expected call of BulkUpdateLastDate.
func (mr *MockProjectEmployeeRepositoryMockRecorder) BulkUpdateLastDate(ctx, assignmentIDs, lastDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateLastDate", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).BulkUpdateLastDate), ctx, assignmentIDs, lastDate)
}

// Count mocks base method.
func (m *MockProjectEmployeeRepository) Count(ctx context.Context, filters domain.ProjectEmployeeFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockProjectEmployeeRepositoryMockRecorder) Count(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).Count), ctx, filters)
}

// CountActiveEmployeesByPaymentSchedule mocks base method.
func (m *MockProjectEmployeeRepository) CountActiveEmployeesByPaymentSchedule(ctx context.Context, schedule domain.PaymentSchedule) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveEmployeesByPaymentSchedule", ctx, schedule)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveEmployeesByPaymentSchedule indicates an expected call of CountActiveEmployeesByPaymentSchedule.
func (mr *MockProjectEmployeeRepositoryMockRecorder) CountActiveEmployeesByPaymentSchedule(ctx, schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveEmployeesByPaymentSchedule", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).CountActiveEmployeesByPaymentSchedule), ctx, schedule)
}

// CountWorkingEmployees mocks base method.
func (m *MockProjectEmployeeRepository) CountWorkingEmployees(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountWorkingEmployees", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountWorkingEmployees indicates an expected call of CountWorkingEmployees.
func (mr *MockProjectEmployeeRepositoryMockRecorder) CountWorkingEmployees(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountWorkingEmployees", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).CountWorkingEmployees), ctx)
}

// Create mocks base method.
func (m *MockProjectEmployeeRepository) Create(ctx context.Context, assignment *domain.ProjectEmployee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, assignment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectEmployeeRepositoryMockRecorder) Create(ctx, assignment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).Create), ctx, assignment)
}

// Delete mocks base method.
func (m *MockProjectEmployeeRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectEmployeeRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).Delete), ctx, id)
}

// DeleteAssignmentsByEmployeeID mocks base method.
func (m *MockProjectEmployeeRepository) DeleteAssignmentsByEmployeeID(ctx context.Context, employeeID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAssignmentsByEmployeeID", ctx, employeeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAssignmentsByEmployeeID indicates an expected call of DeleteAssignmentsByEmployeeID.
func (mr *MockProjectEmployeeRepositoryMockRecorder) DeleteAssignmentsByEmployeeID(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAssignmentsByEmployeeID", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).DeleteAssignmentsByEmployeeID), ctx, employeeID)
}

// DeleteByProjectID mocks base method.
func (m *MockProjectEmployeeRepository) DeleteByProjectID(ctx context.Context, projectID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByProjectID", ctx, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByProjectID indicates an expected call of DeleteByProjectID.
func (mr *MockProjectEmployeeRepositoryMockRecorder) DeleteByProjectID(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByProjectID", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).DeleteByProjectID), ctx, projectID)
}

// EndAssignment mocks base method.
func (m *MockProjectEmployeeRepository) EndAssignment(ctx context.Context, id uint, endDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndAssignment", ctx, id, endDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndAssignment indicates an expected call of EndAssignment.
func (mr *MockProjectEmployeeRepositoryMockRecorder) EndAssignment(ctx, id, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndAssignment", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).EndAssignment), ctx, id, endDate)
}

// GetActiveAssignmentByProjectAndEmployee mocks base method.
func (m *MockProjectEmployeeRepository) GetActiveAssignmentByProjectAndEmployee(ctx context.Context, projectID, employeeID uint) (*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveAssignmentByProjectAndEmployee", ctx, projectID, employeeID)
	ret0, _ := ret[0].(*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveAssignmentByProjectAndEmployee indicates an expected call of GetActiveAssignmentByProjectAndEmployee.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetActiveAssignmentByProjectAndEmployee(ctx, projectID, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveAssignmentByProjectAndEmployee", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetActiveAssignmentByProjectAndEmployee), ctx, projectID, employeeID)
}

// GetActiveAssignments mocks base method.
func (m *MockProjectEmployeeRepository) GetActiveAssignments(ctx context.Context, projectID uint) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveAssignments", ctx, projectID)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveAssignments indicates an expected call of GetActiveAssignments.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetActiveAssignments(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveAssignments", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetActiveAssignments), ctx, projectID)
}

// GetActiveAssignmentsByProjectsAndEmployees mocks base method.
func (m *MockProjectEmployeeRepository) GetActiveAssignmentsByProjectsAndEmployees(ctx context.Context, projectIDs, employeeIDs []uint) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveAssignmentsByProjectsAndEmployees", ctx, projectIDs, employeeIDs)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveAssignmentsByProjectsAndEmployees indicates an expected call of GetActiveAssignmentsByProjectsAndEmployees.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetActiveAssignmentsByProjectsAndEmployees(ctx, projectIDs, employeeIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveAssignmentsByProjectsAndEmployees", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetActiveAssignmentsByProjectsAndEmployees), ctx, projectIDs, employeeIDs)
}

// GetActiveEmployeesForProjectWithCreatorFilter mocks base method.
func (m *MockProjectEmployeeRepository) GetActiveEmployeesForProjectWithCreatorFilter(ctx context.Context, projectID uint, createdBy *uint) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveEmployeesForProjectWithCreatorFilter", ctx, projectID, createdBy)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveEmployeesForProjectWithCreatorFilter indicates an expected call of GetActiveEmployeesForProjectWithCreatorFilter.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetActiveEmployeesForProjectWithCreatorFilter(ctx, projectID, createdBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveEmployeesForProjectWithCreatorFilter", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetActiveEmployeesForProjectWithCreatorFilter), ctx, projectID, createdBy)
}

// GetActiveProjectsForEmployee mocks base method.
func (m *MockProjectEmployeeRepository) GetActiveProjectsForEmployee(ctx context.Context, employeeID uint) ([]*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveProjectsForEmployee", ctx, employeeID)
	ret0, _ := ret[0].([]*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveProjectsForEmployee indicates an expected call of GetActiveProjectsForEmployee.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetActiveProjectsForEmployee(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveProjectsForEmployee", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetActiveProjectsForEmployee), ctx, employeeID)
}

// GetByEmployee mocks base method.
func (m *MockProjectEmployeeRepository) GetByEmployee(ctx context.Context, employeeID uint) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmployee", ctx, employeeID)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmployee indicates an expected call of GetByEmployee.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetByEmployee(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmployee", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetByEmployee), ctx, employeeID)
}

// GetByID mocks base method.
func (m *MockProjectEmployeeRepository) GetByID(ctx context.Context, id uint) (*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetByID), ctx, id)
}

// GetByProject mocks base method.
func (m *MockProjectEmployeeRepository) GetByProject(ctx context.Context, projectID uint) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProject", ctx, projectID)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProject indicates an expected call of GetByProject.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetByProject(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProject", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetByProject), ctx, projectID)
}

// GetByProjectAndEmployee mocks base method.
func (m *MockProjectEmployeeRepository) GetByProjectAndEmployee(ctx context.Context, projectID, employeeID uint) (*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectAndEmployee", ctx, projectID, employeeID)
	ret0, _ := ret[0].(*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectAndEmployee indicates an expected call of GetByProjectAndEmployee.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetByProjectAndEmployee(ctx, projectID, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectAndEmployee", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetByProjectAndEmployee), ctx, projectID, employeeID)
}

// GetCheckInConfiguration mocks base method.
func (m *MockProjectEmployeeRepository) GetCheckInConfiguration(ctx context.Context, query domain.CheckInConfigurationQuery) (*domain.CheckInConfigurationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheckInConfiguration", ctx, query)
	ret0, _ := ret[0].(*domain.CheckInConfigurationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCheckInConfiguration indicates an expected call of GetCheckInConfiguration.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetCheckInConfiguration(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheckInConfiguration", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetCheckInConfiguration), ctx, query)
}

// GetCurrentAssignmentsForProjectForUpdate mocks base method.
func (m *MockProjectEmployeeRepository) GetCurrentAssignmentsForProjectForUpdate(ctx context.Context, projectID uint, asOfDate time.Time) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentAssignmentsForProjectForUpdate", ctx, projectID, asOfDate)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentAssignmentsForProjectForUpdate indicates an expected call of GetCurrentAssignmentsForProjectForUpdate.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetCurrentAssignmentsForProjectForUpdate(ctx, projectID, asOfDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentAssignmentsForProjectForUpdate", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetCurrentAssignmentsForProjectForUpdate), ctx, projectID, asOfDate)
}

// GetCurrentProjectForEmployee mocks base method.
func (m *MockProjectEmployeeRepository) GetCurrentProjectForEmployee(ctx context.Context, employeeID uint) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentProjectForEmployee", ctx, employeeID)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentProjectForEmployee indicates an expected call of GetCurrentProjectForEmployee.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetCurrentProjectForEmployee(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentProjectForEmployee", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetCurrentProjectForEmployee), ctx, employeeID)
}

// GetCurrentProjectsForEmployees mocks base method.
func (m *MockProjectEmployeeRepository) GetCurrentProjectsForEmployees(ctx context.Context, employeeIDs []uint) (map[uint]*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentProjectsForEmployees", ctx, employeeIDs)
	ret0, _ := ret[0].(map[uint]*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentProjectsForEmployees indicates an expected call of GetCurrentProjectsForEmployees.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetCurrentProjectsForEmployees(ctx, employeeIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentProjectsForEmployees", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetCurrentProjectsForEmployees), ctx, employeeIDs)
}

// GetEmployeesByPaymentSchedule mocks base method.
func (m *MockProjectEmployeeRepository) GetEmployeesByPaymentSchedule(ctx context.Context, schedule domain.PaymentSchedule) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeesByPaymentSchedule", ctx, schedule)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeesByPaymentSchedule indicates an expected call of GetEmployeesByPaymentSchedule.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetEmployeesByPaymentSchedule(ctx, schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeesByPaymentSchedule", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetEmployeesByPaymentSchedule), ctx, schedule)
}

// GetEmployeesWithPendingCheckInEnable mocks base method.
func (m *MockProjectEmployeeRepository) GetEmployeesWithPendingCheckInEnable(ctx context.Context, effectiveDate time.Time) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeesWithPendingCheckInEnable", ctx, effectiveDate)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeesWithPendingCheckInEnable indicates an expected call of GetEmployeesWithPendingCheckInEnable.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetEmployeesWithPendingCheckInEnable(ctx, effectiveDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeesWithPendingCheckInEnable", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetEmployeesWithPendingCheckInEnable), ctx, effectiveDate)
}

// GetEmployeesWithPendingScheduleChanges mocks base method.
func (m *MockProjectEmployeeRepository) GetEmployeesWithPendingScheduleChanges(ctx context.Context, effectiveDate time.Time) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeesWithPendingScheduleChanges", ctx, effectiveDate)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeesWithPendingScheduleChanges indicates an expected call of GetEmployeesWithPendingScheduleChanges.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetEmployeesWithPendingScheduleChanges(ctx, effectiveDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeesWithPendingScheduleChanges", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetEmployeesWithPendingScheduleChanges), ctx, effectiveDate)
}

// GetOverlappingAssignments mocks base method.
func (m *MockProjectEmployeeRepository) GetOverlappingAssignments(ctx context.Context, employeeID uint, startDate, endDate *time.Time) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverlappingAssignments", ctx, employeeID, startDate, endDate)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverlappingAssignments indicates an expected call of GetOverlappingAssignments.
func (mr *MockProjectEmployeeRepositoryMockRecorder) GetOverlappingAssignments(ctx, employeeID, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverlappingAssignments", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).GetOverlappingAssignments), ctx, employeeID, startDate, endDate)
}

// HardDeleteAssignmentsByEmployeeID mocks base method.
func (m *MockProjectEmployeeRepository) HardDeleteAssignmentsByEmployeeID(ctx context.Context, employeeID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDeleteAssignmentsByEmployeeID", ctx, employeeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDeleteAssignmentsByEmployeeID indicates an expected call of HardDeleteAssignmentsByEmployeeID.
func (mr *MockProjectEmployeeRepositoryMockRecorder) HardDeleteAssignmentsByEmployeeID(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDeleteAssignmentsByEmployeeID", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).HardDeleteAssignmentsByEmployeeID), ctx, employeeID)
}

// HasAccessViaProject mocks base method.
func (m *MockProjectEmployeeRepository) HasAccessViaProject(ctx context.Context, employeeID, userID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAccessViaProject", ctx, employeeID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasAccessViaProject indicates an expected call of HasAccessViaProject.
func (mr *MockProjectEmployeeRepositoryMockRecorder) HasAccessViaProject(ctx, employeeID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAccessViaProject", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).HasAccessViaProject), ctx, employeeID, userID)
}

// HasActiveFlexiblePaymentScheduleByEmployeeID mocks base method.
func (m *MockProjectEmployeeRepository) HasActiveFlexiblePaymentScheduleByEmployeeID(ctx context.Context, employeeID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveFlexiblePaymentScheduleByEmployeeID", ctx, employeeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasActiveFlexiblePaymentScheduleByEmployeeID indicates an expected call of HasActiveFlexiblePaymentScheduleByEmployeeID.
func (mr *MockProjectEmployeeRepositoryMockRecorder) HasActiveFlexiblePaymentScheduleByEmployeeID(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveFlexiblePaymentScheduleByEmployeeID", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).HasActiveFlexiblePaymentScheduleByEmployeeID), ctx, employeeID)
}

// List mocks base method.
func (m *MockProjectEmployeeRepository) List(ctx context.Context, filters domain.ProjectEmployeeFilters) ([]*domain.ProjectEmployee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*domain.ProjectEmployee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectEmployeeRepositoryMockRecorder) List(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).List), ctx, filters)
}

// Update mocks base method.
func (m *MockProjectEmployeeRepository) Update(ctx context.Context, assignment *domain.ProjectEmployee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, assignment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectEmployeeRepositoryMockRecorder) Update(ctx, assignment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).Update), ctx, assignment)
}

// UpdatePosition mocks base method.
func (m *MockProjectEmployeeRepository) UpdatePosition(ctx context.Context, id uint, position string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePosition", ctx, id, position)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePosition indicates an expected call of UpdatePosition.
func (mr *MockProjectEmployeeRepositoryMockRecorder) UpdatePosition(ctx, id, position interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePosition", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).UpdatePosition), ctx, id, position)
}

// UpdatePositionIfCurrent mocks base method.
func (m *MockProjectEmployeeRepository) UpdatePositionIfCurrent(ctx context.Context, id uint, currentPosition, newPosition string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePositionIfCurrent", ctx, id, currentPosition, newPosition)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePositionIfCurrent indicates an expected call of UpdatePositionIfCurrent.
func (mr *MockProjectEmployeeRepositoryMockRecorder) UpdatePositionIfCurrent(ctx, id, currentPosition, newPosition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePositionIfCurrent", reflect.TypeOf((*MockProjectEmployeeRepository)(nil).UpdatePositionIfCurrent), ctx, id, currentPosition, newPosition)
}
