// Code generated by MockGen. DO NOT EDIT.
// Source: api-server/internal/domain (interfaces: EmployeeRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api-server/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockEmployeeRepository is a mock of EmployeeRepository interface.
type MockEmployeeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmployeeRepositoryMockRecorder
}

// MockEmployeeRepositoryMockRecorder is the mock recorder for MockEmployeeRepository.
type MockEmployeeRepositoryMockRecorder struct {
	mock *MockEmployeeRepository
}

// NewMockEmployeeRepository creates a new mock instance.
func NewMockEmployeeRepository(ctrl *gomock.Controller) *MockEmployeeRepository {
	mock := &MockEmployeeRepository{ctrl: ctrl}
	mock.recorder = &MockEmployeeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmployeeRepository) EXPECT() *MockEmployeeRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockEmployeeRepository) BulkCreate(arg0 context.Context, arg1 []*domain.Employee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockEmployeeRepositoryMockRecorder) BulkCreate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockEmployeeRepository)(nil).BulkCreate), arg0, arg1)
}

// Count mocks base method.
func (m *MockEmployeeRepository) Count(arg0 context.Context, arg1 domain.EmployeeFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockEmployeeRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockEmployeeRepository)(nil).Count), arg0, arg1)
}

// CountEmployeesWithMissingBankDetails mocks base method.
func (m *MockEmployeeRepository) CountEmployeesWithMissingBankDetails(arg0 context.Context, arg1 domain.EmployeeFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEmployeesWithMissingBankDetails", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEmployeesWithMissingBankDetails indicates an expected call of CountEmployeesWithMissingBankDetails.
func (mr *MockEmployeeRepositoryMockRecorder) CountEmployeesWithMissingBankDetails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEmployeesWithMissingBankDetails", reflect.TypeOf((*MockEmployeeRepository)(nil).CountEmployeesWithMissingBankDetails), arg0, arg1)
}

// CountRecentEmployees mocks base method.
func (m *MockEmployeeRepository) CountRecentEmployees(arg0 context.Context, arg1, arg2 time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecentEmployees", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecentEmployees indicates an expected call of CountRecentEmployees.
func (mr *MockEmployeeRepositoryMockRecorder) CountRecentEmployees(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecentEmployees", reflect.TypeOf((*MockEmployeeRepository)(nil).CountRecentEmployees), arg0, arg1, arg2)
}

// CountUnassignedEmployeesAtDate mocks base method.
func (m *MockEmployeeRepository) CountUnassignedEmployeesAtDate(arg0 context.Context, arg1 time.Time, arg2 domain.EmployeeFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnassignedEmployeesAtDate", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnassignedEmployeesAtDate indicates an expected call of CountUnassignedEmployeesAtDate.
func (mr *MockEmployeeRepositoryMockRecorder) CountUnassignedEmployeesAtDate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnassignedEmployeesAtDate", reflect.TypeOf((*MockEmployeeRepository)(nil).CountUnassignedEmployeesAtDate), arg0, arg1, arg2)
}

// Create mocks base method.
func (m *MockEmployeeRepository) Create(arg0 context.Context, arg1 *domain.Employee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEmployeeRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmployeeRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockEmployeeRepository) Delete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEmployeeRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEmployeeRepository)(nil).Delete), arg0, arg1)
}

// ExistsByCCCD mocks base method.
func (m *MockEmployeeRepository) ExistsByCCCD(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByCCCD", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByCCCD indicates an expected call of ExistsByCCCD.
func (mr *MockEmployeeRepositoryMockRecorder) ExistsByCCCD(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByCCCD", reflect.TypeOf((*MockEmployeeRepository)(nil).ExistsByCCCD), arg0, arg1)
}

// ExistsByEmail mocks base method.
func (m *MockEmployeeRepository) ExistsByEmail(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockEmployeeRepositoryMockRecorder) ExistsByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockEmployeeRepository)(nil).ExistsByEmail), arg0, arg1)
}

// GetActiveCountAtDate mocks base method.
func (m *MockEmployeeRepository) GetActiveCountAtDate(arg0 context.Context, arg1 time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveCountAtDate", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveCountAtDate indicates an expected call of GetActiveCountAtDate.
func (mr *MockEmployeeRepositoryMockRecorder) GetActiveCountAtDate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveCountAtDate", reflect.TypeOf((*MockEmployeeRepository)(nil).GetActiveCountAtDate), arg0, arg1)
}

// GetActiveCountAtDateForCreator mocks base method.
func (m *MockEmployeeRepository) GetActiveCountAtDateForCreator(arg0 context.Context, arg1 time.Time, arg2 uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveCountAtDateForCreator", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveCountAtDateForCreator indicates an expected call of GetActiveCountAtDateForCreator.
func (mr *MockEmployeeRepositoryMockRecorder) GetActiveCountAtDateForCreator(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveCountAtDateForCreator", reflect.TypeOf((*MockEmployeeRepository)(nil).GetActiveCountAtDateForCreator), arg0, arg1, arg2)
}

// GetByBankAccountNumber mocks base method.
func (m *MockEmployeeRepository) GetByBankAccountNumber(arg0 context.Context, arg1 string) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBankAccountNumber", arg0, arg1)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBankAccountNumber indicates an expected call of GetByBankAccountNumber.
func (mr *MockEmployeeRepositoryMockRecorder) GetByBankAccountNumber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBankAccountNumber", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByBankAccountNumber), arg0, arg1)
}

// GetByCCCD mocks base method.
func (m *MockEmployeeRepository) GetByCCCD(arg0 context.Context, arg1 string) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCCCD", arg0, arg1)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCCCD indicates an expected call of GetByCCCD.
func (mr *MockEmployeeRepositoryMockRecorder) GetByCCCD(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCCCD", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByCCCD), arg0, arg1)
}

// GetByEmail mocks base method.
func (m *MockEmployeeRepository) GetByEmail(arg0 context.Context, arg1 string) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", arg0, arg1)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockEmployeeRepositoryMockRecorder) GetByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByEmail), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockEmployeeRepository) GetByID(arg0 context.Context, arg1 uint) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEmployeeRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByID), arg0, arg1)
}

// GetByIDForUpdate mocks base method.
func (m *MockEmployeeRepository) GetByIDForUpdate(arg0 context.Context, arg1 uint) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDForUpdate", arg0, arg1)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDForUpdate indicates an expected call of GetByIDForUpdate.
func (mr *MockEmployeeRepositoryMockRecorder) GetByIDForUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDForUpdate", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByIDForUpdate), arg0, arg1)
}

// GetByIDs mocks base method.
func (m *MockEmployeeRepository) GetByIDs(arg0 context.Context, arg1 []int64) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockEmployeeRepositoryMockRecorder) GetByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByIDs), arg0, arg1)
}

// GetByMobile mocks base method.
func (m *MockEmployeeRepository) GetByMobile(arg0 context.Context, arg1 string) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMobile", arg0, arg1)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMobile indicates an expected call of GetByMobile.
func (mr *MockEmployeeRepositoryMockRecorder) GetByMobile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMobile", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByMobile), arg0, arg1)
}

// GetByProject mocks base method.
func (m *MockEmployeeRepository) GetByProject(arg0 context.Context, arg1 uint) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProject", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProject indicates an expected call of GetByProject.
func (mr *MockEmployeeRepositoryMockRecorder) GetByProject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProject", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByProject), arg0, arg1)
}

// GetByProjectWithCreatorFilter mocks base method.
func (m *MockEmployeeRepository) GetByProjectWithCreatorFilter(arg0 context.Context, arg1 uint, arg2 *uint) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectWithCreatorFilter", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectWithCreatorFilter indicates an expected call of GetByProjectWithCreatorFilter.
func (mr *MockEmployeeRepositoryMockRecorder) GetByProjectWithCreatorFilter(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectWithCreatorFilter", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByProjectWithCreatorFilter), arg0, arg1, arg2)
}

// GetByUserID mocks base method.
func (m *MockEmployeeRepository) GetByUserID(arg0 context.Context, arg1 uint) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockEmployeeRepositoryMockRecorder) GetByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByUserID), arg0, arg1)
}

// GetEmployeesSummary mocks base method.
func (m *MockEmployeeRepository) GetEmployeesSummary(arg0 context.Context) (*domain.EmployeesSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeesSummary", arg0)
	ret0, _ := ret[0].(*domain.EmployeesSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeesSummary indicates an expected call of GetEmployeesSummary.
func (mr *MockEmployeeRepositoryMockRecorder) GetEmployeesSummary(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeesSummary", reflect.TypeOf((*MockEmployeeRepository)(nil).GetEmployeesSummary), arg0)
}

// GetEmployeesSummaryForCreator mocks base method.
func (m *MockEmployeeRepository) GetEmployeesSummaryForCreator(arg0 context.Context, arg1 uint) (*domain.EmployeesSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeesSummaryForCreator", arg0, arg1)
	ret0, _ := ret[0].(*domain.EmployeesSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeesSummaryForCreator indicates an expected call of GetEmployeesSummaryForCreator.
func (mr *MockEmployeeRepositoryMockRecorder) GetEmployeesSummaryForCreator(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeesSummaryForCreator", reflect.TypeOf((*MockEmployeeRepository)(nil).GetEmployeesSummaryForCreator), arg0, arg1)
}

// GetEmployeesWithMissingBankDetails mocks base method.
func (m *MockEmployeeRepository) GetEmployeesWithMissingBankDetails(arg0 context.Context, arg1 domain.EmployeeFilters) ([]*domain.EmployeeWithProjects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeesWithMissingBankDetails", arg0, arg1)
	ret0, _ := ret[0].([]*domain.EmployeeWithProjects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeesWithMissingBankDetails indicates an expected call of GetEmployeesWithMissingBankDetails.
func (mr *MockEmployeeRepositoryMockRecorder) GetEmployeesWithMissingBankDetails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeesWithMissingBankDetails", reflect.TypeOf((*MockEmployeeRepository)(nil).GetEmployeesWithMissingBankDetails), arg0, arg1)
}

// GetRecentEmployees mocks base method.
func (m *MockEmployeeRepository) GetRecentEmployees(arg0 context.Context, arg1, arg2 time.Time, arg3 int) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentEmployees", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentEmployees indicates an expected call of GetRecentEmployees.
func (mr *MockEmployeeRepositoryMockRecorder) GetRecentEmployees(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentEmployees", reflect.TypeOf((*MockEmployeeRepository)(nil).GetRecentEmployees), arg0, arg1, arg2, arg3)
}

// GetRecentEmployeesPaginated mocks base method.
func (m *MockEmployeeRepository) GetRecentEmployeesPaginated(arg0 context.Context, arg1, arg2 time.Time, arg3, arg4 int) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentEmployeesPaginated", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentEmployeesPaginated indicates an expected call of GetRecentEmployeesPaginated.
func (mr *MockEmployeeRepositoryMockRecorder) GetRecentEmployeesPaginated(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentEmployeesPaginated", reflect.TypeOf((*MockEmployeeRepository)(nil).GetRecentEmployeesPaginated), arg0, arg1, arg2, arg3, arg4)
}

// GetUnassignedEmployeesAtDate mocks base method.
func (m *MockEmployeeRepository) GetUnassignedEmployeesAtDate(arg0 context.Context, arg1 time.Time, arg2 domain.EmployeeFilters) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnassignedEmployeesAtDate", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnassignedEmployeesAtDate indicates an expected call of GetUnassignedEmployeesAtDate.
func (mr *MockEmployeeRepositoryMockRecorder) GetUnassignedEmployeesAtDate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnassignedEmployeesAtDate", reflect.TypeOf((*MockEmployeeRepository)(nil).GetUnassignedEmployeesAtDate), arg0, arg1, arg2)
}

// HardDelete mocks base method.
func (m *MockEmployeeRepository) HardDelete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockEmployeeRepositoryMockRecorder) HardDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockEmployeeRepository)(nil).HardDelete), arg0, arg1)
}

// List mocks base method.
func (m *MockEmployeeRepository) List(arg0 context.Context, arg1 domain.EmployeeFilters) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEmployeeRepositoryMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEmployeeRepository)(nil).List), arg0, arg1)
}

// ListAccessibleIDs mocks base method.
func (m *MockEmployeeRepository) ListAccessibleIDs(arg0 context.Context, arg1 uint) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessibleIDs", arg0, arg1)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessibleIDs indicates an expected call of ListAccessibleIDs.
func (mr *MockEmployeeRepositoryMockRecorder) ListAccessibleIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessibleIDs", reflect.TypeOf((*MockEmployeeRepository)(nil).ListAccessibleIDs), arg0, arg1)
}

// ListByMobile mocks base method.
func (m *MockEmployeeRepository) ListByMobile(arg0 context.Context, arg1 string) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMobile", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMobile indicates an expected call of ListByMobile.
func (mr *MockEmployeeRepositoryMockRecorder) ListByMobile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMobile", reflect.TypeOf((*MockEmployeeRepository)(nil).ListByMobile), arg0, arg1)
}

// ListWithAllProjects mocks base method.
func (m *MockEmployeeRepository) ListWithAllProjects(arg0 context.Context, arg1 domain.EmployeeFilters) ([]*domain.EmployeeWithProjects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithAllProjects", arg0, arg1)
	ret0, _ := ret[0].([]*domain.EmployeeWithProjects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithAllProjects indicates an expected call of ListWithAllProjects.
func (mr *MockEmployeeRepositoryMockRecorder) ListWithAllProjects(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithAllProjects", reflect.TypeOf((*MockEmployeeRepository)(nil).ListWithAllProjects), arg0, arg1)
}

// ListWithProjects mocks base method.
func (m *MockEmployeeRepository) ListWithProjects(arg0 context.Context, arg1 domain.EmployeeFilters) ([]*domain.EmployeeWithProject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithProjects", arg0, arg1)
	ret0, _ := ret[0].([]*domain.EmployeeWithProject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithProjects indicates an expected call of ListWithProjects.
func (mr *MockEmployeeRepositoryMockRecorder) ListWithProjects(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithProjects", reflect.TypeOf((*MockEmployeeRepository)(nil).ListWithProjects), arg0, arg1)
}

// SearchEmployees mocks base method.
func (m *MockEmployeeRepository) SearchEmployees(arg0 context.Context, arg1 string, arg2 int) ([]*domain.EmployeeWithProject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchEmployees", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.EmployeeWithProject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchEmployees indicates an expected call of SearchEmployees.
func (mr *MockEmployeeRepositoryMockRecorder) SearchEmployees(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchEmployees", reflect.TypeOf((*MockEmployeeRepository)(nil).SearchEmployees), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockEmployeeRepository) Update(arg0 context.Context, arg1 *domain.Employee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEmployeeRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEmployeeRepository)(nil).Update), arg0, arg1)
}

// UpdateColumns mocks base method.
func (m *MockEmployeeRepository) UpdateColumns(arg0 context.Context, arg1 uint, arg2 map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateColumns", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateColumns indicates an expected call of UpdateColumns.
func (mr *MockEmployeeRepositoryMockRecorder) UpdateColumns(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateColumns", reflect.TypeOf((*MockEmployeeRepository)(nil).UpdateColumns), arg0, arg1, arg2)
}
