// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/bank.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api-server/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBankRepository is a mock of BankRepository interface.
type MockBankRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBankRepositoryMockRecorder
}

// MockBankRepositoryMockRecorder is the mock recorder for MockBankRepository.
type MockBankRepositoryMockRecorder struct {
	mock *MockBankRepository
}

// NewMockBankRepository creates a new mock instance.
func NewMockBankRepository(ctrl *gomock.Controller) *MockBankRepository {
	mock := &MockBankRepository{ctrl: ctrl}
	mock.recorder = &MockBankRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankRepository) EXPECT() *MockBankRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockBankRepository) Count(ctx context.Context, filters domain.BankFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockBankRepositoryMockRecorder) Count(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockBankRepository)(nil).Count), ctx, filters)
}

// Create mocks base method.
func (m *MockBankRepository) Create(ctx context.Context, bank *domain.Bank) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, bank)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBankRepositoryMockRecorder) Create(ctx, bank interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBankRepository)(nil).Create), ctx, bank)
}

// Delete mocks base method.
func (m *MockBankRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBankRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBankRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockBankRepository) GetByID(ctx context.Context, id uint) (*domain.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBankRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBankRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockBankRepository) List(ctx context.Context, filters domain.BankFilters) ([]*domain.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*domain.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBankRepositoryMockRecorder) List(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBankRepository)(nil).List), ctx, filters)
}

// SearchByBranchName mocks base method.
func (m *MockBankRepository) SearchByBranchName(ctx context.Context, searchTerm string, limit int) ([]*domain.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByBranchName", ctx, searchTerm, limit)
	ret0, _ := ret[0].([]*domain.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByBranchName indicates an expected call of SearchByBranchName.
func (mr *MockBankRepositoryMockRecorder) SearchByBranchName(ctx, searchTerm, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByBranchName", reflect.TypeOf((*MockBankRepository)(nil).SearchByBranchName), ctx, searchTerm, limit)
}

// Update mocks base method.
func (m *MockBankRepository) Update(ctx context.Context, bank *domain.Bank) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, bank)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBankRepositoryMockRecorder) Update(ctx, bank interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBankRepository)(nil).Update), ctx, bank)
}
