// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/security.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api-server/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockBlacklistedTokenRepository is a mock of BlacklistedTokenRepository interface.
type MockBlacklistedTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlacklistedTokenRepositoryMockRecorder
}

// MockBlacklistedTokenRepositoryMockRecorder is the mock recorder for MockBlacklistedTokenRepository.
type MockBlacklistedTokenRepositoryMockRecorder struct {
	mock *MockBlacklistedTokenRepository
}

// NewMockBlacklistedTokenRepository creates a new mock instance.
func NewMockBlacklistedTokenRepository(ctrl *gomock.Controller) *MockBlacklistedTokenRepository {
	mock := &MockBlacklistedTokenRepository{ctrl: ctrl}
	mock.recorder = &MockBlacklistedTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlacklistedTokenRepository) EXPECT() *MockBlacklistedTokenRepositoryMockRecorder {
	return m.recorder
}

// BlacklistToken mocks base method.
func (m *MockBlacklistedTokenRepository) BlacklistToken(ctx context.Context, jti string, userID uint, expiresAt time.Time, reason domain.BlacklistReason) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlacklistToken", ctx, jti, userID, expiresAt, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlacklistToken indicates an expected call of BlacklistToken.
func (mr *MockBlacklistedTokenRepositoryMockRecorder) BlacklistToken(ctx, jti, userID, expiresAt, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlacklistToken", reflect.TypeOf((*MockBlacklistedTokenRepository)(nil).BlacklistToken), ctx, jti, userID, expiresAt, reason)
}

// Count mocks base method.
func (m *MockBlacklistedTokenRepository) Count(ctx context.Context, filters domain.BlacklistFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockBlacklistedTokenRepositoryMockRecorder) Count(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockBlacklistedTokenRepository)(nil).Count), ctx, filters)
}

// Create mocks base method.
func (m *MockBlacklistedTokenRepository) Create(ctx context.Context, token *domain.BlacklistedToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBlacklistedTokenRepositoryMockRecorder) Create(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlacklistedTokenRepository)(nil).Create), ctx, token)
}

// DeleteExpired mocks base method.
func (m *MockBlacklistedTokenRepository) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockBlacklistedTokenRepositoryMockRecorder) DeleteExpired(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockBlacklistedTokenRepository)(nil).DeleteExpired), ctx)
}

// GetByJTI mocks base method.
func (m *MockBlacklistedTokenRepository) GetByJTI(ctx context.Context, jti string) (*domain.BlacklistedToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByJTI", ctx, jti)
	ret0, _ := ret[0].(*domain.BlacklistedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByJTI indicates an expected call of GetByJTI.
func (mr *MockBlacklistedTokenRepositoryMockRecorder) GetByJTI(ctx, jti interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByJTI", reflect.TypeOf((*MockBlacklistedTokenRepository)(nil).GetByJTI), ctx, jti)
}

// GetByUser mocks base method.
func (m *MockBlacklistedTokenRepository) GetByUser(ctx context.Context, userID uint) ([]*domain.BlacklistedToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", ctx, userID)
	ret0, _ := ret[0].([]*domain.BlacklistedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockBlacklistedTokenRepositoryMockRecorder) GetByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockBlacklistedTokenRepository)(nil).GetByUser), ctx, userID)
}

// IsBlacklisted mocks base method.
func (m *MockBlacklistedTokenRepository) IsBlacklisted(ctx context.Context, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBlacklisted", ctx, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBlacklisted indicates an expected call of IsBlacklisted.
func (mr *MockBlacklistedTokenRepositoryMockRecorder) IsBlacklisted(ctx, jti interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBlacklisted", reflect.TypeOf((*MockBlacklistedTokenRepository)(nil).IsBlacklisted), ctx, jti)
}

// List mocks base method.
func (m *MockBlacklistedTokenRepository) List(ctx context.Context, filters domain.BlacklistFilters) ([]*domain.BlacklistedToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*domain.BlacklistedToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBlacklistedTokenRepositoryMockRecorder) List(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBlacklistedTokenRepository)(nil).List), ctx, filters)
}

// MockAuditLogRepository is a mock of AuditLogRepository interface.
type MockAuditLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogRepositoryMockRecorder
}

// MockAuditLogRepositoryMockRecorder is the mock recorder for MockAuditLogRepository.
type MockAuditLogRepositoryMockRecorder struct {
	mock *MockAuditLogRepository
}

// NewMockAuditLogRepository creates a new mock instance.
func NewMockAuditLogRepository(ctrl *gomock.Controller) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{ctrl: ctrl}
	mock.recorder = &MockAuditLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogRepository) EXPECT() *MockAuditLogRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockAuditLogRepository) Count(ctx context.Context, filters domain.AuditFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockAuditLogRepositoryMockRecorder) Count(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockAuditLogRepository)(nil).Count), ctx, filters)
}

// Create mocks base method.
func (m *MockAuditLogRepository) Create(ctx context.Context, log *domain.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuditLogRepositoryMockRecorder) Create(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuditLogRepository)(nil).Create), ctx, log)
}

// DeleteOldLogs mocks base method.
func (m *MockAuditLogRepository) DeleteOldLogs(ctx context.Context, olderThan time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldLogs", ctx, olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldLogs indicates an expected call of DeleteOldLogs.
func (mr *MockAuditLogRepositoryMockRecorder) DeleteOldLogs(ctx, olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldLogs", reflect.TypeOf((*MockAuditLogRepository)(nil).DeleteOldLogs), ctx, olderThan)
}

// GetByID mocks base method.
func (m *MockAuditLogRepository) GetByID(ctx context.Context, id uint) (*domain.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuditLogRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuditLogRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockAuditLogRepository) List(ctx context.Context, filters domain.AuditFilters) ([]*domain.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*domain.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAuditLogRepositoryMockRecorder) List(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuditLogRepository)(nil).List), ctx, filters)
}
