// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/employee.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api-server/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockEmployeeRepository is a mock of EmployeeRepository interface.
type MockEmployeeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmployeeRepositoryMockRecorder
}

// MockEmployeeRepositoryMockRecorder is the mock recorder for MockEmployeeRepository.
type MockEmployeeRepositoryMockRecorder struct {
	mock *MockEmployeeRepository
}

// NewMockEmployeeRepository creates a new mock instance.
func NewMockEmployeeRepository(ctrl *gomock.Controller) *MockEmployeeRepository {
	mock := &MockEmployeeRepository{ctrl: ctrl}
	mock.recorder = &MockEmployeeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmployeeRepository) EXPECT() *MockEmployeeRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockEmployeeRepository) BulkCreate(ctx context.Context, employees []*domain.Employee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, employees)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockEmployeeRepositoryMockRecorder) BulkCreate(ctx, employees interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockEmployeeRepository)(nil).BulkCreate), ctx, employees)
}

// Count mocks base method.
func (m *MockEmployeeRepository) Count(ctx context.Context, filters domain.EmployeeFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockEmployeeRepositoryMockRecorder) Count(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockEmployeeRepository)(nil).Count), ctx, filters)
}

// CountEmployeesWithMissingBankDetails mocks base method.
func (m *MockEmployeeRepository) CountEmployeesWithMissingBankDetails(ctx context.Context, filters domain.EmployeeFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEmployeesWithMissingBankDetails", ctx, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEmployeesWithMissingBankDetails indicates an expected call of CountEmployeesWithMissingBankDetails.
func (mr *MockEmployeeRepositoryMockRecorder) CountEmployeesWithMissingBankDetails(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEmployeesWithMissingBankDetails", reflect.TypeOf((*MockEmployeeRepository)(nil).CountEmployeesWithMissingBankDetails), ctx, filters)
}

// CountRecentEmployees mocks base method.
func (m *MockEmployeeRepository) CountRecentEmployees(ctx context.Context, startDate, endDate time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecentEmployees", ctx, startDate, endDate)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecentEmployees indicates an expected call of CountRecentEmployees.
func (mr *MockEmployeeRepositoryMockRecorder) CountRecentEmployees(ctx, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecentEmployees", reflect.TypeOf((*MockEmployeeRepository)(nil).CountRecentEmployees), ctx, startDate, endDate)
}

// CountUnassignedEmployeesAtDate mocks base method.
func (m *MockEmployeeRepository) CountUnassignedEmployeesAtDate(ctx context.Context, atDate time.Time, filters domain.EmployeeFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnassignedEmployeesAtDate", ctx, atDate, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnassignedEmployeesAtDate indicates an expected call of CountUnassignedEmployeesAtDate.
func (mr *MockEmployeeRepositoryMockRecorder) CountUnassignedEmployeesAtDate(ctx, atDate, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnassignedEmployeesAtDate", reflect.TypeOf((*MockEmployeeRepository)(nil).CountUnassignedEmployeesAtDate), ctx, atDate, filters)
}

// Create mocks base method.
func (m *MockEmployeeRepository) Create(ctx context.Context, employee *domain.Employee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, employee)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEmployeeRepositoryMockRecorder) Create(ctx, employee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmployeeRepository)(nil).Create), ctx, employee)
}

// Delete mocks base method.
func (m *MockEmployeeRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEmployeeRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEmployeeRepository)(nil).Delete), ctx, id)
}

// ExistsByCCCD mocks base method.
func (m *MockEmployeeRepository) ExistsByCCCD(ctx context.Context, cccd string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByCCCD", ctx, cccd)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByCCCD indicates an expected call of ExistsByCCCD.
func (mr *MockEmployeeRepositoryMockRecorder) ExistsByCCCD(ctx, cccd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByCCCD", reflect.TypeOf((*MockEmployeeRepository)(nil).ExistsByCCCD), ctx, cccd)
}

// ExistsByEmail mocks base method.
func (m *MockEmployeeRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockEmployeeRepositoryMockRecorder) ExistsByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockEmployeeRepository)(nil).ExistsByEmail), ctx, email)
}

// GetActiveCountAtDate mocks base method.
func (m *MockEmployeeRepository) GetActiveCountAtDate(ctx context.Context, date time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveCountAtDate", ctx, date)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveCountAtDate indicates an expected call of GetActiveCountAtDate.
func (mr *MockEmployeeRepositoryMockRecorder) GetActiveCountAtDate(ctx, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveCountAtDate", reflect.TypeOf((*MockEmployeeRepository)(nil).GetActiveCountAtDate), ctx, date)
}

// GetActiveCountAtDateForCreator mocks base method.
func (m *MockEmployeeRepository) GetActiveCountAtDateForCreator(ctx context.Context, date time.Time, createdBy uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveCountAtDateForCreator", ctx, date, createdBy)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveCountAtDateForCreator indicates an expected call of GetActiveCountAtDateForCreator.
func (mr *MockEmployeeRepositoryMockRecorder) GetActiveCountAtDateForCreator(ctx, date, createdBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveCountAtDateForCreator", reflect.TypeOf((*MockEmployeeRepository)(nil).GetActiveCountAtDateForCreator), ctx, date, createdBy)
}

// GetByBankAccountNumber mocks base method.
func (m *MockEmployeeRepository) GetByBankAccountNumber(ctx context.Context, bankAccountNumber string) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBankAccountNumber", ctx, bankAccountNumber)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBankAccountNumber indicates an expected call of GetByBankAccountNumber.
func (mr *MockEmployeeRepositoryMockRecorder) GetByBankAccountNumber(ctx, bankAccountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBankAccountNumber", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByBankAccountNumber), ctx, bankAccountNumber)
}

// GetByCCCD mocks base method.
func (m *MockEmployeeRepository) GetByCCCD(ctx context.Context, cccd string) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCCCD", ctx, cccd)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCCCD indicates an expected call of GetByCCCD.
func (mr *MockEmployeeRepositoryMockRecorder) GetByCCCD(ctx, cccd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCCCD", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByCCCD), ctx, cccd)
}

// GetByEmail mocks base method.
func (m *MockEmployeeRepository) GetByEmail(ctx context.Context, email string) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockEmployeeRepositoryMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockEmployeeRepository) GetByID(ctx context.Context, id uint) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEmployeeRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByID), ctx, id)
}

// GetByIDForUpdate mocks base method.
func (m *MockEmployeeRepository) GetByIDForUpdate(ctx context.Context, id uint) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDForUpdate", ctx, id)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDForUpdate indicates an expected call of GetByIDForUpdate.
func (mr *MockEmployeeRepositoryMockRecorder) GetByIDForUpdate(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDForUpdate", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByIDForUpdate), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockEmployeeRepository) GetByIDs(ctx context.Context, ids []int64) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockEmployeeRepositoryMockRecorder) GetByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByIDs), ctx, ids)
}

// GetByMobile mocks base method.
func (m *MockEmployeeRepository) GetByMobile(ctx context.Context, mobile string) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMobile", ctx, mobile)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMobile indicates an expected call of GetByMobile.
func (mr *MockEmployeeRepositoryMockRecorder) GetByMobile(ctx, mobile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMobile", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByMobile), ctx, mobile)
}

// GetByProject mocks base method.
func (m *MockEmployeeRepository) GetByProject(ctx context.Context, projectID uint) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProject", ctx, projectID)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProject indicates an expected call of GetByProject.
func (mr *MockEmployeeRepositoryMockRecorder) GetByProject(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProject", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByProject), ctx, projectID)
}

// GetByProjectWithCreatorFilter mocks base method.
func (m *MockEmployeeRepository) GetByProjectWithCreatorFilter(ctx context.Context, projectID uint, createdBy *uint) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectWithCreatorFilter", ctx, projectID, createdBy)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectWithCreatorFilter indicates an expected call of GetByProjectWithCreatorFilter.
func (mr *MockEmployeeRepositoryMockRecorder) GetByProjectWithCreatorFilter(ctx, projectID, createdBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectWithCreatorFilter", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByProjectWithCreatorFilter), ctx, projectID, createdBy)
}

// GetByUserID mocks base method.
func (m *MockEmployeeRepository) GetByUserID(ctx context.Context, userID uint) (*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockEmployeeRepositoryMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockEmployeeRepository)(nil).GetByUserID), ctx, userID)
}

// GetEmployeesSummary mocks base method.
func (m *MockEmployeeRepository) GetEmployeesSummary(ctx context.Context) (*domain.EmployeesSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeesSummary", ctx)
	ret0, _ := ret[0].(*domain.EmployeesSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeesSummary indicates an expected call of GetEmployeesSummary.
func (mr *MockEmployeeRepositoryMockRecorder) GetEmployeesSummary(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeesSummary", reflect.TypeOf((*MockEmployeeRepository)(nil).GetEmployeesSummary), ctx)
}

// GetEmployeesSummaryForCreator mocks base method.
func (m *MockEmployeeRepository) GetEmployeesSummaryForCreator(ctx context.Context, createdBy uint) (*domain.EmployeesSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeesSummaryForCreator", ctx, createdBy)
	ret0, _ := ret[0].(*domain.EmployeesSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeesSummaryForCreator indicates an expected call of GetEmployeesSummaryForCreator.
func (mr *MockEmployeeRepositoryMockRecorder) GetEmployeesSummaryForCreator(ctx, createdBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeesSummaryForCreator", reflect.TypeOf((*MockEmployeeRepository)(nil).GetEmployeesSummaryForCreator), ctx, createdBy)
}

// GetEmployeesWithMissingBankDetails mocks base method.
func (m *MockEmployeeRepository) GetEmployeesWithMissingBankDetails(ctx context.Context, filters domain.EmployeeFilters) ([]*domain.EmployeeWithProjects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeesWithMissingBankDetails", ctx, filters)
	ret0, _ := ret[0].([]*domain.EmployeeWithProjects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeesWithMissingBankDetails indicates an expected call of GetEmployeesWithMissingBankDetails.
func (mr *MockEmployeeRepositoryMockRecorder) GetEmployeesWithMissingBankDetails(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeesWithMissingBankDetails", reflect.TypeOf((*MockEmployeeRepository)(nil).GetEmployeesWithMissingBankDetails), ctx, filters)
}

// GetRecentEmployees mocks base method.
func (m *MockEmployeeRepository) GetRecentEmployees(ctx context.Context, startDate, endDate time.Time, limit int) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentEmployees", ctx, startDate, endDate, limit)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentEmployees indicates an expected call of GetRecentEmployees.
func (mr *MockEmployeeRepositoryMockRecorder) GetRecentEmployees(ctx, startDate, endDate, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentEmployees", reflect.TypeOf((*MockEmployeeRepository)(nil).GetRecentEmployees), ctx, startDate, endDate, limit)
}

// GetRecentEmployeesPaginated mocks base method.
func (m *MockEmployeeRepository) GetRecentEmployeesPaginated(ctx context.Context, startDate, endDate time.Time, limit, offset int) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentEmployeesPaginated", ctx, startDate, endDate, limit, offset)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentEmployeesPaginated indicates an expected call of GetRecentEmployeesPaginated.
func (mr *MockEmployeeRepositoryMockRecorder) GetRecentEmployeesPaginated(ctx, startDate, endDate, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentEmployeesPaginated", reflect.TypeOf((*MockEmployeeRepository)(nil).GetRecentEmployeesPaginated), ctx, startDate, endDate, limit, offset)
}

// GetUnassignedEmployeesAtDate mocks base method.
func (m *MockEmployeeRepository) GetUnassignedEmployeesAtDate(ctx context.Context, atDate time.Time, filters domain.EmployeeFilters) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnassignedEmployeesAtDate", ctx, atDate, filters)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnassignedEmployeesAtDate indicates an expected call of GetUnassignedEmployeesAtDate.
func (mr *MockEmployeeRepositoryMockRecorder) GetUnassignedEmployeesAtDate(ctx, atDate, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnassignedEmployeesAtDate", reflect.TypeOf((*MockEmployeeRepository)(nil).GetUnassignedEmployeesAtDate), ctx, atDate, filters)
}

// List mocks base method.
func (m *MockEmployeeRepository) List(ctx context.Context, filters domain.EmployeeFilters) ([]*domain.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*domain.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEmployeeRepositoryMockRecorder) List(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEmployeeRepository)(nil).List), ctx, filters)
}

// ListWithAllProjects mocks base method.
func (m *MockEmployeeRepository) ListWithAllProjects(ctx context.Context, filters domain.EmployeeFilters) ([]*domain.EmployeeWithProjects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithAllProjects", ctx, filters)
	ret0, _ := ret[0].([]*domain.EmployeeWithProjects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithAllProjects indicates an expected call of ListWithAllProjects.
func (mr *MockEmployeeRepositoryMockRecorder) ListWithAllProjects(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithAllProjects", reflect.TypeOf((*MockEmployeeRepository)(nil).ListWithAllProjects), ctx, filters)
}

// ListWithProjects mocks base method.
func (m *MockEmployeeRepository) ListWithProjects(ctx context.Context, filters domain.EmployeeFilters) ([]*domain.EmployeeWithProject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithProjects", ctx, filters)
	ret0, _ := ret[0].([]*domain.EmployeeWithProject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithProjects indicates an expected call of ListWithProjects.
func (mr *MockEmployeeRepositoryMockRecorder) ListWithProjects(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithProjects", reflect.TypeOf((*MockEmployeeRepository)(nil).ListWithProjects), ctx, filters)
}

// SearchEmployees mocks base method.
func (m *MockEmployeeRepository) SearchEmployees(ctx context.Context, search string, limit int) ([]*domain.EmployeeWithProject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchEmployees", ctx, search, limit)
	ret0, _ := ret[0].([]*domain.EmployeeWithProject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchEmployees indicates an expected call of SearchEmployees.
func (mr *MockEmployeeRepositoryMockRecorder) SearchEmployees(ctx, search, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchEmployees", reflect.TypeOf((*MockEmployeeRepository)(nil).SearchEmployees), ctx, search, limit)
}

// Update mocks base method.
func (m *MockEmployeeRepository) Update(ctx context.Context, employee *domain.Employee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, employee)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEmployeeRepositoryMockRecorder) Update(ctx, employee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEmployeeRepository)(nil).Update), ctx, employee)
}

// UpdateColumns mocks base method.
func (m *MockEmployeeRepository) UpdateColumns(ctx context.Context, id uint, columns map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateColumns", ctx, id, columns)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateColumns indicates an expected call of UpdateColumns.
func (mr *MockEmployeeRepositoryMockRecorder) UpdateColumns(ctx, id, columns interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateColumns", reflect.TypeOf((*MockEmployeeRepository)(nil).UpdateColumns), ctx, id, columns)
}
