// Code generated by MockGen. DO NOT EDIT.
// Source: api-server/internal/domain (interfaces: UserRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api-server/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockUserRepository) Count(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockUserRepositoryMockRecorder) Count(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUserRepository)(nil).Count), arg0)
}

// CountActiveEmployeesBySchedule mocks base method.
func (m *MockUserRepository) CountActiveEmployeesBySchedule(arg0 context.Context, arg1, arg2 time.Time) (int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveEmployeesBySchedule", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CountActiveEmployeesBySchedule indicates an expected call of CountActiveEmployeesBySchedule.
func (mr *MockUserRepositoryMockRecorder) CountActiveEmployeesBySchedule(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveEmployeesBySchedule", reflect.TypeOf((*MockUserRepository)(nil).CountActiveEmployeesBySchedule), arg0, arg1, arg2)
}

// CountByRole mocks base method.
func (m *MockUserRepository) CountByRole(arg0 context.Context, arg1 domain.UserRole) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByRole", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByRole indicates an expected call of CountByRole.
func (mr *MockUserRepositoryMockRecorder) CountByRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByRole", reflect.TypeOf((*MockUserRepository)(nil).CountByRole), arg0, arg1)
}

// CountRecentLogins mocks base method.
func (m *MockUserRepository) CountRecentLogins(arg0 context.Context, arg1 time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecentLogins", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecentLogins indicates an expected call of CountRecentLogins.
func (mr *MockUserRepositoryMockRecorder) CountRecentLogins(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecentLogins", reflect.TypeOf((*MockUserRepository)(nil).CountRecentLogins), arg0, arg1)
}

// CountUsersWithNullLastLogin mocks base method.
func (m *MockUserRepository) CountUsersWithNullLastLogin(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsersWithNullLastLogin", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsersWithNullLastLogin indicates an expected call of CountUsersWithNullLastLogin.
func (mr *MockUserRepositoryMockRecorder) CountUsersWithNullLastLogin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsersWithNullLastLogin", reflect.TypeOf((*MockUserRepository)(nil).CountUsersWithNullLastLogin), arg0)
}

// Create mocks base method.
func (m *MockUserRepository) Create(arg0 context.Context, arg1 *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), arg0, arg1)
}

// ExistsByUsername mocks base method.
func (m *MockUserRepository) ExistsByUsername(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByUsername", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByUsername indicates an expected call of ExistsByUsername.
func (mr *MockUserRepositoryMockRecorder) ExistsByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByUsername", reflect.TypeOf((*MockUserRepository)(nil).ExistsByUsername), arg0, arg1)
}

// FindUsersWithNullLastLogin mocks base method.
func (m *MockUserRepository) FindUsersWithNullLastLogin(arg0 context.Context, arg1, arg2 int) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsersWithNullLastLogin", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUsersWithNullLastLogin indicates an expected call of FindUsersWithNullLastLogin.
func (mr *MockUserRepositoryMockRecorder) FindUsersWithNullLastLogin(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsersWithNullLastLogin", reflect.TypeOf((*MockUserRepository)(nil).FindUsersWithNullLastLogin), arg0, arg1, arg2)
}

// GetActiveEmployeesBySchedule mocks base method.
func (m *MockUserRepository) GetActiveEmployeesBySchedule(arg0 context.Context, arg1, arg2 time.Time, arg3 string) ([]*domain.ActiveEmployeeUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveEmployeesBySchedule", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.ActiveEmployeeUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveEmployeesBySchedule indicates an expected call of GetActiveEmployeesBySchedule.
func (mr *MockUserRepositoryMockRecorder) GetActiveEmployeesBySchedule(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveEmployeesBySchedule", reflect.TypeOf((*MockUserRepository)(nil).GetActiveEmployeesBySchedule), arg0, arg1, arg2, arg3)
}

// GetByCCCD mocks base method.
func (m *MockUserRepository) GetByCCCD(arg0 context.Context, arg1 string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCCCD", arg0, arg1)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCCCD indicates an expected call of GetByCCCD.
func (mr *MockUserRepositoryMockRecorder) GetByCCCD(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCCCD", reflect.TypeOf((*MockUserRepository)(nil).GetByCCCD), arg0, arg1)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(arg0 context.Context, arg1 string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", arg0, arg1)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(arg0 context.Context, arg1 uint) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), arg0, arg1)
}

// GetByIDs mocks base method.
func (m *MockUserRepository) GetByIDs(arg0 context.Context, arg1 []uint) (map[uint]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", arg0, arg1)
	ret0, _ := ret[0].(map[uint]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockUserRepositoryMockRecorder) GetByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockUserRepository)(nil).GetByIDs), arg0, arg1)
}

// GetByMobile mocks base method.
func (m *MockUserRepository) GetByMobile(arg0 context.Context, arg1 string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMobile", arg0, arg1)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMobile indicates an expected call of GetByMobile.
func (mr *MockUserRepositoryMockRecorder) GetByMobile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMobile", reflect.TypeOf((*MockUserRepository)(nil).GetByMobile), arg0, arg1)
}

// GetByUsername mocks base method.
func (m *MockUserRepository) GetByUsername(arg0 context.Context, arg1 string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", arg0, arg1)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepositoryMockRecorder) GetByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetByUsername), arg0, arg1)
}

// GetByUsernameIncludingDeleted mocks base method.
func (m *MockUserRepository) GetByUsernameIncludingDeleted(arg0 context.Context, arg1 string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsernameIncludingDeleted", arg0, arg1)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsernameIncludingDeleted indicates an expected call of GetByUsernameIncludingDeleted.
func (mr *MockUserRepositoryMockRecorder) GetByUsernameIncludingDeleted(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsernameIncludingDeleted", reflect.TypeOf((*MockUserRepository)(nil).GetByUsernameIncludingDeleted), arg0, arg1)
}

// GetUsernamesByPrefix mocks base method.
func (m *MockUserRepository) GetUsernamesByPrefix(arg0 context.Context, arg1 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsernamesByPrefix", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsernamesByPrefix indicates an expected call of GetUsernamesByPrefix.
func (mr *MockUserRepositoryMockRecorder) GetUsernamesByPrefix(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsernamesByPrefix", reflect.TypeOf((*MockUserRepository)(nil).GetUsernamesByPrefix), arg0, arg1)
}

// List mocks base method.
func (m *MockUserRepository) List(arg0 context.Context, arg1, arg2 int) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List), arg0, arg1, arg2)
}

// ListByRole mocks base method.
func (m *MockUserRepository) ListByRole(arg0 context.Context, arg1 domain.UserRole) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRole", arg0, arg1)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRole indicates an expected call of ListByRole.
func (mr *MockUserRepositoryMockRecorder) ListByRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRole", reflect.TypeOf((*MockUserRepository)(nil).ListByRole), arg0, arg1)
}

// ListWithFilters mocks base method.
func (m *MockUserRepository) ListWithFilters(arg0 context.Context, arg1 *domain.UserRole, arg2 string, arg3 []uint, arg4 bool, arg5, arg6 string, arg7, arg8 int) ([]*domain.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithFilters", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWithFilters indicates an expected call of ListWithFilters.
func (mr *MockUserRepositoryMockRecorder) ListWithFilters(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithFilters", reflect.TypeOf((*MockUserRepository)(nil).ListWithFilters), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
}

// Restore mocks base method.
func (m *MockUserRepository) Restore(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockUserRepositoryMockRecorder) Restore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockUserRepository)(nil).Restore), arg0, arg1)
}

// Update mocks base method.
func (m *MockUserRepository) Update(arg0 context.Context, arg1 *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), arg0, arg1)
}

// UpdateLastLogin mocks base method.
func (m *MockUserRepository) UpdateLastLogin(arg0 context.Context, arg1 uint, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockUserRepositoryMockRecorder) UpdateLastLogin(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockUserRepository)(nil).UpdateLastLogin), arg0, arg1, arg2)
}

// UpdateOTPLockout mocks base method.
func (m *MockUserRepository) UpdateOTPLockout(arg0 context.Context, arg1 uint, arg2 int, arg3 *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOTPLockout", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOTPLockout indicates an expected call of UpdateOTPLockout.
func (mr *MockUserRepositoryMockRecorder) UpdateOTPLockout(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOTPLockout", reflect.TypeOf((*MockUserRepository)(nil).UpdateOTPLockout), arg0, arg1, arg2, arg3)
}

// UpdatePasswordAndInvalidateSessions mocks base method.
func (m *MockUserRepository) UpdatePasswordAndInvalidateSessions(arg0 context.Context, arg1 uint, arg2 string, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordAndInvalidateSessions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordAndInvalidateSessions indicates an expected call of UpdatePasswordAndInvalidateSessions.
func (mr *MockUserRepositoryMockRecorder) UpdatePasswordAndInvalidateSessions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordAndInvalidateSessions", reflect.TypeOf((*MockUserRepository)(nil).UpdatePasswordAndInvalidateSessions), arg0, arg1, arg2, arg3)
}

// UpdateTokensInvalidBefore mocks base method.
func (m *MockUserRepository) UpdateTokensInvalidBefore(arg0 context.Context, arg1 uint, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokensInvalidBefore", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokensInvalidBefore indicates an expected call of UpdateTokensInvalidBefore.
func (mr *MockUserRepositoryMockRecorder) UpdateTokensInvalidBefore(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokensInvalidBefore", reflect.TypeOf((*MockUserRepository)(nil).UpdateTokensInvalidBefore), arg0, arg1, arg2)
}
