// Code generated by MockGen. DO NOT EDIT.
// Source: api-server/internal/domain (interfaces: TimesheetRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api-server/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTimesheetRepository is a mock of TimesheetRepository interface.
type MockTimesheetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTimesheetRepositoryMockRecorder
}

// MockTimesheetRepositoryMockRecorder is the mock recorder for MockTimesheetRepository.
type MockTimesheetRepositoryMockRecorder struct {
	mock *MockTimesheetRepository
}

// NewMockTimesheetRepository creates a new mock instance.
func NewMockTimesheetRepository(ctrl *gomock.Controller) *MockTimesheetRepository {
	mock := &MockTimesheetRepository{ctrl: ctrl}
	mock.recorder = &MockTimesheetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimesheetRepository) EXPECT() *MockTimesheetRepositoryMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockTimesheetRepository) Approve(arg0 context.Context, arg1, arg2 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockTimesheetRepositoryMockRecorder) Approve(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockTimesheetRepository)(nil).Approve), arg0, arg1, arg2)
}

// BatchUpdatePaymentStatusToFailed mocks base method.
func (m *MockTimesheetRepository) BatchUpdatePaymentStatusToFailed(arg0 context.Context, arg1 interface{}, arg2 []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdatePaymentStatusToFailed", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdatePaymentStatusToFailed indicates an expected call of BatchUpdatePaymentStatusToFailed.
func (mr *MockTimesheetRepositoryMockRecorder) BatchUpdatePaymentStatusToFailed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdatePaymentStatusToFailed", reflect.TypeOf((*MockTimesheetRepository)(nil).BatchUpdatePaymentStatusToFailed), arg0, arg1, arg2)
}

// BulkApprove mocks base method.
func (m *MockTimesheetRepository) BulkApprove(arg0 context.Context, arg1 []uint, arg2 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkApprove", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkApprove indicates an expected call of BulkApprove.
func (mr *MockTimesheetRepositoryMockRecorder) BulkApprove(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkApprove", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkApprove), arg0, arg1, arg2)
}

// BulkCreate mocks base method.
func (m *MockTimesheetRepository) BulkCreate(arg0 context.Context, arg1 []*domain.Timesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockTimesheetRepositoryMockRecorder) BulkCreate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkCreate), arg0, arg1)
}

// BulkReject mocks base method.
func (m *MockTimesheetRepository) BulkReject(arg0 context.Context, arg1 []uint, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkReject", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkReject indicates an expected call of BulkReject.
func (mr *MockTimesheetRepositoryMockRecorder) BulkReject(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkReject", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkReject), arg0, arg1, arg2)
}

// BulkUpdate mocks base method.
func (m *MockTimesheetRepository) BulkUpdate(arg0 context.Context, arg1 []*domain.Timesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdate indicates an expected call of BulkUpdate.
func (mr *MockTimesheetRepositoryMockRecorder) BulkUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdate", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkUpdate), arg0, arg1)
}

// BulkUpdatePaymentStatus mocks base method.
func (m *MockTimesheetRepository) BulkUpdatePaymentStatus(arg0 context.Context, arg1 []domain.PaymentStatusUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdatePaymentStatus", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdatePaymentStatus indicates an expected call of BulkUpdatePaymentStatus.
func (mr *MockTimesheetRepositoryMockRecorder) BulkUpdatePaymentStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdatePaymentStatus", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkUpdatePaymentStatus), arg0, arg1)
}

// BulkUpdateRevenuePaid mocks base method.
func (m *MockTimesheetRepository) BulkUpdateRevenuePaid(arg0 context.Context, arg1 []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateRevenuePaid", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateRevenuePaid indicates an expected call of BulkUpdateRevenuePaid.
func (mr *MockTimesheetRepositoryMockRecorder) BulkUpdateRevenuePaid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateRevenuePaid", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkUpdateRevenuePaid), arg0, arg1)
}

// BulkUpdateRevenueReceivable mocks base method.
func (m *MockTimesheetRepository) BulkUpdateRevenueReceivable(arg0 context.Context, arg1 map[uint]int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateRevenueReceivable", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateRevenueReceivable indicates an expected call of BulkUpdateRevenueReceivable.
func (mr *MockTimesheetRepositoryMockRecorder) BulkUpdateRevenueReceivable(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateRevenueReceivable", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkUpdateRevenueReceivable), arg0, arg1)
}

// BulkUpdateTransactionID mocks base method.
func (m *MockTimesheetRepository) BulkUpdateTransactionID(arg0 context.Context, arg1 uint, arg2 []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateTransactionID", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateTransactionID indicates an expected call of BulkUpdateTransactionID.
func (mr *MockTimesheetRepositoryMockRecorder) BulkUpdateTransactionID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateTransactionID", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkUpdateTransactionID), arg0, arg1, arg2)
}

// Count mocks base method.
func (m *MockTimesheetRepository) Count(arg0 context.Context, arg1 domain.TimesheetFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockTimesheetRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockTimesheetRepository)(nil).Count), arg0, arg1)
}

// CountDistinctEmployees mocks base method.
func (m *MockTimesheetRepository) CountDistinctEmployees(arg0 context.Context, arg1 domain.TimesheetFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDistinctEmployees", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDistinctEmployees indicates an expected call of CountDistinctEmployees.
func (mr *MockTimesheetRepositoryMockRecorder) CountDistinctEmployees(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDistinctEmployees", reflect.TypeOf((*MockTimesheetRepository)(nil).CountDistinctEmployees), arg0, arg1)
}

// CountDistinctEmployeesPaidInPeriod mocks base method.
func (m *MockTimesheetRepository) CountDistinctEmployeesPaidInPeriod(arg0 context.Context, arg1, arg2 time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDistinctEmployeesPaidInPeriod", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDistinctEmployeesPaidInPeriod indicates an expected call of CountDistinctEmployeesPaidInPeriod.
func (mr *MockTimesheetRepositoryMockRecorder) CountDistinctEmployeesPaidInPeriod(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDistinctEmployeesPaidInPeriod", reflect.TypeOf((*MockTimesheetRepository)(nil).CountDistinctEmployeesPaidInPeriod), arg0, arg1, arg2)
}

// CountDistinctWorkingDays mocks base method.
func (m *MockTimesheetRepository) CountDistinctWorkingDays(arg0 context.Context, arg1, arg2 uint, arg3, arg4 time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDistinctWorkingDays", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDistinctWorkingDays indicates an expected call of CountDistinctWorkingDays.
func (mr *MockTimesheetRepositoryMockRecorder) CountDistinctWorkingDays(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDistinctWorkingDays", reflect.TypeOf((*MockTimesheetRepository)(nil).CountDistinctWorkingDays), arg0, arg1, arg2, arg3, arg4)
}

// CountEmployeesPaidInLast30Days mocks base method.
func (m *MockTimesheetRepository) CountEmployeesPaidInLast30Days(arg0 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEmployeesPaidInLast30Days", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEmployeesPaidInLast30Days indicates an expected call of CountEmployeesPaidInLast30Days.
func (mr *MockTimesheetRepositoryMockRecorder) CountEmployeesPaidInLast30Days(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEmployeesPaidInLast30Days", reflect.TypeOf((*MockTimesheetRepository)(nil).CountEmployeesPaidInLast30Days), arg0)
}

// CountTimesheets mocks base method.
func (m *MockTimesheetRepository) CountTimesheets(arg0 context.Context, arg1, arg2 uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTimesheets", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTimesheets indicates an expected call of CountTimesheets.
func (mr *MockTimesheetRepositoryMockRecorder) CountTimesheets(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTimesheets", reflect.TypeOf((*MockTimesheetRepository)(nil).CountTimesheets), arg0, arg1, arg2)
}

// CountTimesheetsByEmployeeID mocks base method.
func (m *MockTimesheetRepository) CountTimesheetsByEmployeeID(arg0 context.Context, arg1 uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTimesheetsByEmployeeID", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTimesheetsByEmployeeID indicates an expected call of CountTimesheetsByEmployeeID.
func (mr *MockTimesheetRepositoryMockRecorder) CountTimesheetsByEmployeeID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTimesheetsByEmployeeID", reflect.TypeOf((*MockTimesheetRepository)(nil).CountTimesheetsByEmployeeID), arg0, arg1)
}

// CountUnsettledPaidTimesheets mocks base method.
func (m *MockTimesheetRepository) CountUnsettledPaidTimesheets(arg0 context.Context, arg1 uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnsettledPaidTimesheets", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnsettledPaidTimesheets indicates an expected call of CountUnsettledPaidTimesheets.
func (mr *MockTimesheetRepositoryMockRecorder) CountUnsettledPaidTimesheets(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnsettledPaidTimesheets", reflect.TypeOf((*MockTimesheetRepository)(nil).CountUnsettledPaidTimesheets), arg0, arg1)
}

// Create mocks base method.
func (m *MockTimesheetRepository) Create(arg0 context.Context, arg1 *domain.Timesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTimesheetRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTimesheetRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockTimesheetRepository) Delete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTimesheetRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTimesheetRepository)(nil).Delete), arg0, arg1)
}

// DeleteByProjectID mocks base method.
func (m *MockTimesheetRepository) DeleteByProjectID(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByProjectID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByProjectID indicates an expected call of DeleteByProjectID.
func (mr *MockTimesheetRepositoryMockRecorder) DeleteByProjectID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByProjectID", reflect.TypeOf((*MockTimesheetRepository)(nil).DeleteByProjectID), arg0, arg1)
}

// GetAccrualCohort mocks base method.
func (m *MockTimesheetRepository) GetAccrualCohort(arg0 context.Context, arg1 domain.TimesheetFilters) ([]domain.TimesheetAccrualDailyRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccrualCohort", arg0, arg1)
	ret0, _ := ret[0].([]domain.TimesheetAccrualDailyRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccrualCohort indicates an expected call of GetAccrualCohort.
func (mr *MockTimesheetRepositoryMockRecorder) GetAccrualCohort(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccrualCohort", reflect.TypeOf((*MockTimesheetRepository)(nil).GetAccrualCohort), arg0, arg1)
}

// GetApprovedSalaryTotal mocks base method.
func (m *MockTimesheetRepository) GetApprovedSalaryTotal(arg0 context.Context, arg1, arg2 time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApprovedSalaryTotal", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApprovedSalaryTotal indicates an expected call of GetApprovedSalaryTotal.
func (mr *MockTimesheetRepositoryMockRecorder) GetApprovedSalaryTotal(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApprovedSalaryTotal", reflect.TypeOf((*MockTimesheetRepository)(nil).GetApprovedSalaryTotal), arg0, arg1, arg2)
}

// GetByEmployee mocks base method.
func (m *MockTimesheetRepository) GetByEmployee(arg0 context.Context, arg1 uint, arg2, arg3 time.Time) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmployee", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmployee indicates an expected call of GetByEmployee.
func (mr *MockTimesheetRepositoryMockRecorder) GetByEmployee(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmployee", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByEmployee), arg0, arg1, arg2, arg3)
}

// GetByEmployeeAndPeriod mocks base method.
func (m *MockTimesheetRepository) GetByEmployeeAndPeriod(arg0 context.Context, arg1 uint, arg2, arg3 time.Time) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmployeeAndPeriod", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmployeeAndPeriod indicates an expected call of GetByEmployeeAndPeriod.
func (mr *MockTimesheetRepositoryMockRecorder) GetByEmployeeAndPeriod(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmployeeAndPeriod", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByEmployeeAndPeriod), arg0, arg1, arg2, arg3)
}

// GetByEmployeeDateCombos mocks base method.
func (m *MockTimesheetRepository) GetByEmployeeDateCombos(arg0 context.Context, arg1 []domain.EmployeeDateCombo) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmployeeDateCombos", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmployeeDateCombos indicates an expected call of GetByEmployeeDateCombos.
func (mr *MockTimesheetRepositoryMockRecorder) GetByEmployeeDateCombos(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmployeeDateCombos", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByEmployeeDateCombos), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockTimesheetRepository) GetByID(arg0 context.Context, arg1 uint) (*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTimesheetRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByID), arg0, arg1)
}

// GetByIDs mocks base method.
func (m *MockTimesheetRepository) GetByIDs(arg0 context.Context, arg1 []uint) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockTimesheetRepositoryMockRecorder) GetByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByIDs), arg0, arg1)
}

// GetByIDsWithoutRelations mocks base method.
func (m *MockTimesheetRepository) GetByIDsWithoutRelations(arg0 context.Context, arg1 []uint) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDsWithoutRelations", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDsWithoutRelations indicates an expected call of GetByIDsWithoutRelations.
func (mr *MockTimesheetRepositoryMockRecorder) GetByIDsWithoutRelations(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDsWithoutRelations", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByIDsWithoutRelations), arg0, arg1)
}

// GetByProject mocks base method.
func (m *MockTimesheetRepository) GetByProject(arg0 context.Context, arg1 uint, arg2, arg3 time.Time) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProject", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProject indicates an expected call of GetByProject.
func (mr *MockTimesheetRepositoryMockRecorder) GetByProject(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProject", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByProject), arg0, arg1, arg2, arg3)
}

// GetByProjectAndEmployee mocks base method.
func (m *MockTimesheetRepository) GetByProjectAndEmployee(arg0 context.Context, arg1, arg2 uint, arg3, arg4 time.Time) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectAndEmployee", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectAndEmployee indicates an expected call of GetByProjectAndEmployee.
func (mr *MockTimesheetRepositoryMockRecorder) GetByProjectAndEmployee(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectAndEmployee", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByProjectAndEmployee), arg0, arg1, arg2, arg3, arg4)
}

// GetByProjectEmployeeDate mocks base method.
func (m *MockTimesheetRepository) GetByProjectEmployeeDate(arg0 context.Context, arg1, arg2 uint, arg3 time.Time) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectEmployeeDate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectEmployeeDate indicates an expected call of GetByProjectEmployeeDate.
func (mr *MockTimesheetRepositoryMockRecorder) GetByProjectEmployeeDate(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectEmployeeDate", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByProjectEmployeeDate), arg0, arg1, arg2, arg3)
}

// GetByProjectEmployeeDateHourType mocks base method.
func (m *MockTimesheetRepository) GetByProjectEmployeeDateHourType(arg0 context.Context, arg1, arg2 uint, arg3 time.Time, arg4 string) (*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectEmployeeDateHourType", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectEmployeeDateHourType indicates an expected call of GetByProjectEmployeeDateHourType.
func (mr *MockTimesheetRepositoryMockRecorder) GetByProjectEmployeeDateHourType(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectEmployeeDateHourType", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByProjectEmployeeDateHourType), arg0, arg1, arg2, arg3, arg4)
}

// GetByProjectEmployeeDatePaytype mocks base method.
func (m *MockTimesheetRepository) GetByProjectEmployeeDatePaytype(arg0 context.Context, arg1, arg2 uint, arg3 time.Time, arg4 string) (*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectEmployeeDatePaytype", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectEmployeeDatePaytype indicates an expected call of GetByProjectEmployeeDatePaytype.
func (mr *MockTimesheetRepositoryMockRecorder) GetByProjectEmployeeDatePaytype(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectEmployeeDatePaytype", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByProjectEmployeeDatePaytype), arg0, arg1, arg2, arg3, arg4)
}

// GetByTransactionID mocks base method.
func (m *MockTimesheetRepository) GetByTransactionID(arg0 context.Context, arg1 uint) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTransactionID", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTransactionID indicates an expected call of GetByTransactionID.
func (mr *MockTimesheetRepositoryMockRecorder) GetByTransactionID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTransactionID", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByTransactionID), arg0, arg1)
}

// GetEmployeeCurrentWeekHours mocks base method.
func (m *MockTimesheetRepository) GetEmployeeCurrentWeekHours(arg0 context.Context, arg1 uint) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeCurrentWeekHours", arg0, arg1)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeCurrentWeekHours indicates an expected call of GetEmployeeCurrentWeekHours.
func (mr *MockTimesheetRepositoryMockRecorder) GetEmployeeCurrentWeekHours(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeCurrentWeekHours", reflect.TypeOf((*MockTimesheetRepository)(nil).GetEmployeeCurrentWeekHours), arg0, arg1)
}

// GetEmployeeMonthlyPayrollSummary mocks base method.
func (m *MockTimesheetRepository) GetEmployeeMonthlyPayrollSummary(arg0 context.Context, arg1 uint) (*domain.PayrollSummaryAggregated, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeMonthlyPayrollSummary", arg0, arg1)
	ret0, _ := ret[0].(*domain.PayrollSummaryAggregated)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeMonthlyPayrollSummary indicates an expected call of GetEmployeeMonthlyPayrollSummary.
func (mr *MockTimesheetRepositoryMockRecorder) GetEmployeeMonthlyPayrollSummary(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeMonthlyPayrollSummary", reflect.TypeOf((*MockTimesheetRepository)(nil).GetEmployeeMonthlyPayrollSummary), arg0, arg1)
}

// GetEmployeeTimesheetSummaryAggregated mocks base method.
func (m *MockTimesheetRepository) GetEmployeeTimesheetSummaryAggregated(arg0 context.Context, arg1 uint) (*domain.TimesheetSummaryAggregated, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeTimesheetSummaryAggregated", arg0, arg1)
	ret0, _ := ret[0].(*domain.TimesheetSummaryAggregated)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeTimesheetSummaryAggregated indicates an expected call of GetEmployeeTimesheetSummaryAggregated.
func (mr *MockTimesheetRepositoryMockRecorder) GetEmployeeTimesheetSummaryAggregated(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeTimesheetSummaryAggregated", reflect.TypeOf((*MockTimesheetRepository)(nil).GetEmployeeTimesheetSummaryAggregated), arg0, arg1)
}

// GetEntryTableData mocks base method.
func (m *MockTimesheetRepository) GetEntryTableData(arg0 context.Context, arg1 uint, arg2 []uint, arg3, arg4 time.Time) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntryTableData", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntryTableData indicates an expected call of GetEntryTableData.
func (mr *MockTimesheetRepositoryMockRecorder) GetEntryTableData(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntryTableData", reflect.TypeOf((*MockTimesheetRepository)(nil).GetEntryTableData), arg0, arg1, arg2, arg3, arg4)
}

// GetFirstPaidTimesheetDate mocks base method.
func (m *MockTimesheetRepository) GetFirstPaidTimesheetDate(arg0 context.Context) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstPaidTimesheetDate", arg0)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstPaidTimesheetDate indicates an expected call of GetFirstPaidTimesheetDate.
func (mr *MockTimesheetRepositoryMockRecorder) GetFirstPaidTimesheetDate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstPaidTimesheetDate", reflect.TypeOf((*MockTimesheetRepository)(nil).GetFirstPaidTimesheetDate), arg0)
}

// GetLatestTimesheetDate mocks base method.
func (m *MockTimesheetRepository) GetLatestTimesheetDate(arg0 context.Context, arg1, arg2 uint) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestTimesheetDate", arg0, arg1, arg2)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestTimesheetDate indicates an expected call of GetLatestTimesheetDate.
func (mr *MockTimesheetRepositoryMockRecorder) GetLatestTimesheetDate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestTimesheetDate", reflect.TypeOf((*MockTimesheetRepository)(nil).GetLatestTimesheetDate), arg0, arg1, arg2)
}

// GetPaidSalaryByEmployee mocks base method.
func (m *MockTimesheetRepository) GetPaidSalaryByEmployee(arg0 context.Context, arg1, arg2 time.Time) (map[uint]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaidSalaryByEmployee", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[uint]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaidSalaryByEmployee indicates an expected call of GetPaidSalaryByEmployee.
func (mr *MockTimesheetRepositoryMockRecorder) GetPaidSalaryByEmployee(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaidSalaryByEmployee", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPaidSalaryByEmployee), arg0, arg1, arg2)
}

// GetPaidSalaryForMonth mocks base method.
func (m *MockTimesheetRepository) GetPaidSalaryForMonth(arg0 context.Context, arg1, arg2 time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaidSalaryForMonth", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaidSalaryForMonth indicates an expected call of GetPaidSalaryForMonth.
func (mr *MockTimesheetRepositoryMockRecorder) GetPaidSalaryForMonth(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaidSalaryForMonth", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPaidSalaryForMonth), arg0, arg1, arg2)
}

// GetPaidTimesheetsInDateRange mocks base method.
func (m *MockTimesheetRepository) GetPaidTimesheetsInDateRange(arg0 context.Context, arg1, arg2 time.Time, arg3 *[]*domain.Timesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaidTimesheetsInDateRange", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPaidTimesheetsInDateRange indicates an expected call of GetPaidTimesheetsInDateRange.
func (mr *MockTimesheetRepositoryMockRecorder) GetPaidTimesheetsInDateRange(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaidTimesheetsInDateRange", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPaidTimesheetsInDateRange), arg0, arg1, arg2, arg3)
}

// GetPaymentHistories mocks base method.
func (m *MockTimesheetRepository) GetPaymentHistories(arg0 context.Context, arg1 domain.PaymentHistoryFilters) ([]*domain.PaymentHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentHistories", arg0, arg1)
	ret0, _ := ret[0].([]*domain.PaymentHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPaymentHistories indicates an expected call of GetPaymentHistories.
func (mr *MockTimesheetRepositoryMockRecorder) GetPaymentHistories(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentHistories", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPaymentHistories), arg0, arg1)
}

// GetPendingApprovalCount mocks base method.
func (m *MockTimesheetRepository) GetPendingApprovalCount(arg0 context.Context, arg1, arg2 time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingApprovalCount", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingApprovalCount indicates an expected call of GetPendingApprovalCount.
func (mr *MockTimesheetRepositoryMockRecorder) GetPendingApprovalCount(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingApprovalCount", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPendingApprovalCount), arg0, arg1, arg2)
}

// GetPendingSalaryForMonth mocks base method.
func (m *MockTimesheetRepository) GetPendingSalaryForMonth(arg0 context.Context, arg1, arg2 time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingSalaryForMonth", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingSalaryForMonth indicates an expected call of GetPendingSalaryForMonth.
func (mr *MockTimesheetRepositoryMockRecorder) GetPendingSalaryForMonth(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingSalaryForMonth", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPendingSalaryForMonth), arg0, arg1, arg2)
}

// GetPendingSalaryForMonthBySchedule mocks base method.
func (m *MockTimesheetRepository) GetPendingSalaryForMonthBySchedule(arg0 context.Context, arg1, arg2 time.Time, arg3 domain.PaymentSchedule) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingSalaryForMonthBySchedule", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingSalaryForMonthBySchedule indicates an expected call of GetPendingSalaryForMonthBySchedule.
func (mr *MockTimesheetRepositoryMockRecorder) GetPendingSalaryForMonthBySchedule(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingSalaryForMonthBySchedule", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPendingSalaryForMonthBySchedule), arg0, arg1, arg2, arg3)
}

// GetProjectsForEmployeeOnDate mocks base method.
func (m *MockTimesheetRepository) GetProjectsForEmployeeOnDate(arg0 context.Context, arg1 uint, arg2 time.Time) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectsForEmployeeOnDate", arg0, arg1, arg2)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectsForEmployeeOnDate indicates an expected call of GetProjectsForEmployeeOnDate.
func (mr *MockTimesheetRepositoryMockRecorder) GetProjectsForEmployeeOnDate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectsForEmployeeOnDate", reflect.TypeOf((*MockTimesheetRepository)(nil).GetProjectsForEmployeeOnDate), arg0, arg1, arg2)
}

// GetSummaryByProject mocks base method.
func (m *MockTimesheetRepository) GetSummaryByProject(arg0 context.Context, arg1 uint, arg2, arg3 time.Time) (*domain.TimesheetSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummaryByProject", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.TimesheetSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummaryByProject indicates an expected call of GetSummaryByProject.
func (mr *MockTimesheetRepositoryMockRecorder) GetSummaryByProject(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummaryByProject", reflect.TypeOf((*MockTimesheetRepository)(nil).GetSummaryByProject), arg0, arg1, arg2, arg3)
}

// GetSummaryStats mocks base method.
func (m *MockTimesheetRepository) GetSummaryStats(arg0 context.Context, arg1 domain.TimesheetFilters) (*domain.TimesheetSummaryStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummaryStats", arg0, arg1)
	ret0, _ := ret[0].(*domain.TimesheetSummaryStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummaryStats indicates an expected call of GetSummaryStats.
func (mr *MockTimesheetRepositoryMockRecorder) GetSummaryStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummaryStats", reflect.TypeOf((*MockTimesheetRepository)(nil).GetSummaryStats), arg0, arg1)
}

// GetTimesheetDatesByIDs mocks base method.
func (m *MockTimesheetRepository) GetTimesheetDatesByIDs(arg0 context.Context, arg1 []uint) (map[uint]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimesheetDatesByIDs", arg0, arg1)
	ret0, _ := ret[0].(map[uint]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimesheetDatesByIDs indicates an expected call of GetTimesheetDatesByIDs.
func (mr *MockTimesheetRepositoryMockRecorder) GetTimesheetDatesByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimesheetDatesByIDs", reflect.TypeOf((*MockTimesheetRepository)(nil).GetTimesheetDatesByIDs), arg0, arg1)
}

// GetTotalPaidSalary mocks base method.
func (m *MockTimesheetRepository) GetTotalPaidSalary(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalPaidSalary", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalPaidSalary indicates an expected call of GetTotalPaidSalary.
func (mr *MockTimesheetRepositoryMockRecorder) GetTotalPaidSalary(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalPaidSalary", reflect.TypeOf((*MockTimesheetRepository)(nil).GetTotalPaidSalary), arg0)
}

// HardDelete mocks base method.
func (m *MockTimesheetRepository) HardDelete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockTimesheetRepositoryMockRecorder) HardDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockTimesheetRepository)(nil).HardDelete), arg0, arg1)
}

// HardDeleteOperationalByEmployeeID mocks base method.
func (m *MockTimesheetRepository) HardDeleteOperationalByEmployeeID(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDeleteOperationalByEmployeeID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDeleteOperationalByEmployeeID indicates an expected call of HardDeleteOperationalByEmployeeID.
func (mr *MockTimesheetRepositoryMockRecorder) HardDeleteOperationalByEmployeeID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDeleteOperationalByEmployeeID", reflect.TypeOf((*MockTimesheetRepository)(nil).HardDeleteOperationalByEmployeeID), arg0, arg1)
}

// HasNonEditableTimesheetsAfterDate mocks base method.
func (m *MockTimesheetRepository) HasNonEditableTimesheetsAfterDate(arg0 context.Context, arg1, arg2 uint, arg3 time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasNonEditableTimesheetsAfterDate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasNonEditableTimesheetsAfterDate indicates an expected call of HasNonEditableTimesheetsAfterDate.
func (mr *MockTimesheetRepositoryMockRecorder) HasNonEditableTimesheetsAfterDate(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNonEditableTimesheetsAfterDate", reflect.TypeOf((*MockTimesheetRepository)(nil).HasNonEditableTimesheetsAfterDate), arg0, arg1, arg2, arg3)
}

// HasProtectedTimesheetsByEmployeeID mocks base method.
func (m *MockTimesheetRepository) HasProtectedTimesheetsByEmployeeID(arg0 context.Context, arg1 uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasProtectedTimesheetsByEmployeeID", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasProtectedTimesheetsByEmployeeID indicates an expected call of HasProtectedTimesheetsByEmployeeID.
func (mr *MockTimesheetRepositoryMockRecorder) HasProtectedTimesheetsByEmployeeID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasProtectedTimesheetsByEmployeeID", reflect.TypeOf((*MockTimesheetRepository)(nil).HasProtectedTimesheetsByEmployeeID), arg0, arg1)
}

// HasTimesheetsAfterDate mocks base method.
func (m *MockTimesheetRepository) HasTimesheetsAfterDate(arg0 context.Context, arg1, arg2 uint, arg3 time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTimesheetsAfterDate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasTimesheetsAfterDate indicates an expected call of HasTimesheetsAfterDate.
func (mr *MockTimesheetRepositoryMockRecorder) HasTimesheetsAfterDate(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTimesheetsAfterDate", reflect.TypeOf((*MockTimesheetRepository)(nil).HasTimesheetsAfterDate), arg0, arg1, arg2, arg3)
}

// HasTimesheetsForAssignment mocks base method.
func (m *MockTimesheetRepository) HasTimesheetsForAssignment(arg0 context.Context, arg1, arg2 uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTimesheetsForAssignment", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasTimesheetsForAssignment indicates an expected call of HasTimesheetsForAssignment.
func (mr *MockTimesheetRepositoryMockRecorder) HasTimesheetsForAssignment(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTimesheetsForAssignment", reflect.TypeOf((*MockTimesheetRepository)(nil).HasTimesheetsForAssignment), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockTimesheetRepository) List(arg0 context.Context, arg1 domain.TimesheetFilters) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTimesheetRepositoryMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTimesheetRepository)(nil).List), arg0, arg1)
}

// ListGroupedByEmployee mocks base method.
func (m *MockTimesheetRepository) ListGroupedByEmployee(arg0 context.Context, arg1 domain.TimesheetFilters) ([]domain.EmployeeGroupResult, []*domain.Timesheet, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupedByEmployee", arg0, arg1)
	ret0, _ := ret[0].([]domain.EmployeeGroupResult)
	ret1, _ := ret[1].([]*domain.Timesheet)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListGroupedByEmployee indicates an expected call of ListGroupedByEmployee.
func (mr *MockTimesheetRepositoryMockRecorder) ListGroupedByEmployee(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupedByEmployee", reflect.TypeOf((*MockTimesheetRepository)(nil).ListGroupedByEmployee), arg0, arg1)
}

// Reject mocks base method.
func (m *MockTimesheetRepository) Reject(arg0 context.Context, arg1 uint, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reject indicates an expected call of Reject.
func (mr *MockTimesheetRepositoryMockRecorder) Reject(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockTimesheetRepository)(nil).Reject), arg0, arg1, arg2)
}

// Reset mocks base method.
func (m *MockTimesheetRepository) Reset(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockTimesheetRepositoryMockRecorder) Reset(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockTimesheetRepository)(nil).Reset), arg0, arg1)
}

// SetForcePayroll mocks base method.
func (m *MockTimesheetRepository) SetForcePayroll(arg0 context.Context, arg1 uint, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetForcePayroll", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetForcePayroll indicates an expected call of SetForcePayroll.
func (mr *MockTimesheetRepositoryMockRecorder) SetForcePayroll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetForcePayroll", reflect.TypeOf((*MockTimesheetRepository)(nil).SetForcePayroll), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockTimesheetRepository) Update(arg0 context.Context, arg1 *domain.Timesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTimesheetRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTimesheetRepository)(nil).Update), arg0, arg1)
}
