// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/payrate.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api-server/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockPayrateRepository is a mock of PayrateRepository interface.
type MockPayrateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPayrateRepositoryMockRecorder
}

// MockPayrateRepositoryMockRecorder is the mock recorder for MockPayrateRepository.
type MockPayrateRepositoryMockRecorder struct {
	mock *MockPayrateRepository
}

// NewMockPayrateRepository creates a new mock instance.
func NewMockPayrateRepository(ctrl *gomock.Controller) *MockPayrateRepository {
	mock := &MockPayrateRepository{ctrl: ctrl}
	mock.recorder = &MockPayrateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayrateRepository) EXPECT() *MockPayrateRepositoryMockRecorder {
	return m.recorder
}

// CloseActiveByProject mocks base method.
func (m *MockPayrateRepository) CloseActiveByProject(ctx context.Context, tx interface{}, projectID uint, toDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseActiveByProject", ctx, tx, projectID, toDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseActiveByProject indicates an expected call of CloseActiveByProject.
func (mr *MockPayrateRepositoryMockRecorder) CloseActiveByProject(ctx, tx, projectID, toDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseActiveByProject", reflect.TypeOf((*MockPayrateRepository)(nil).CloseActiveByProject), ctx, tx, projectID, toDate)
}

// Count mocks base method.
func (m *MockPayrateRepository) Count(ctx context.Context, filters domain.PayrateFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockPayrateRepositoryMockRecorder) Count(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockPayrateRepository)(nil).Count), ctx, filters)
}

// Create mocks base method.
func (m *MockPayrateRepository) Create(ctx context.Context, payrate *domain.Payrate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, payrate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPayrateRepositoryMockRecorder) Create(ctx, payrate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPayrateRepository)(nil).Create), ctx, payrate)
}

// CreateWithTx mocks base method.
func (m *MockPayrateRepository) CreateWithTx(ctx context.Context, tx interface{}, payrate *domain.Payrate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, tx, payrate)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockPayrateRepositoryMockRecorder) CreateWithTx(ctx, tx, payrate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockPayrateRepository)(nil).CreateWithTx), ctx, tx, payrate)
}

// Delete mocks base method.
func (m *MockPayrateRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPayrateRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPayrateRepository)(nil).Delete), ctx, id)
}

// DeleteActiveByProject mocks base method.
func (m *MockPayrateRepository) DeleteActiveByProject(ctx context.Context, tx interface{}, projectID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActiveByProject", ctx, tx, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteActiveByProject indicates an expected call of DeleteActiveByProject.
func (mr *MockPayrateRepositoryMockRecorder) DeleteActiveByProject(ctx, tx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActiveByProject", reflect.TypeOf((*MockPayrateRepository)(nil).DeleteActiveByProject), ctx, tx, projectID)
}

// EndActivePayrates mocks base method.
func (m *MockPayrateRepository) EndActivePayrates(ctx context.Context, projectID uint, endDate time.Time, excludeID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndActivePayrates", ctx, projectID, endDate, excludeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndActivePayrates indicates an expected call of EndActivePayrates.
func (mr *MockPayrateRepositoryMockRecorder) EndActivePayrates(ctx, projectID, endDate, excludeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndActivePayrates", reflect.TypeOf((*MockPayrateRepository)(nil).EndActivePayrates), ctx, projectID, endDate, excludeID)
}

// FindActiveByProject mocks base method.
func (m *MockPayrateRepository) FindActiveByProject(ctx context.Context, tx interface{}, projectID uint) ([]*domain.Payrate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByProject", ctx, tx, projectID)
	ret0, _ := ret[0].([]*domain.Payrate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByProject indicates an expected call of FindActiveByProject.
func (mr *MockPayrateRepositoryMockRecorder) FindActiveByProject(ctx, tx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByProject", reflect.TypeOf((*MockPayrateRepository)(nil).FindActiveByProject), ctx, tx, projectID)
}

// GetActiveByProject mocks base method.
func (m *MockPayrateRepository) GetActiveByProject(ctx context.Context, projectID uint, date time.Time) ([]*domain.Payrate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByProject", ctx, projectID, date)
	ret0, _ := ret[0].([]*domain.Payrate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByProject indicates an expected call of GetActiveByProject.
func (mr *MockPayrateRepositoryMockRecorder) GetActiveByProject(ctx, projectID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByProject", reflect.TypeOf((*MockPayrateRepository)(nil).GetActiveByProject), ctx, projectID, date)
}

// GetActiveByProjectAndDate mocks base method.
func (m *MockPayrateRepository) GetActiveByProjectAndDate(ctx context.Context, projectID uint, date time.Time) (*domain.Payrate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByProjectAndDate", ctx, projectID, date)
	ret0, _ := ret[0].(*domain.Payrate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByProjectAndDate indicates an expected call of GetActiveByProjectAndDate.
func (mr *MockPayrateRepositoryMockRecorder) GetActiveByProjectAndDate(ctx, projectID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByProjectAndDate", reflect.TypeOf((*MockPayrateRepository)(nil).GetActiveByProjectAndDate), ctx, projectID, date)
}

// GetByID mocks base method.
func (m *MockPayrateRepository) GetByID(ctx context.Context, id uint) (*domain.Payrate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Payrate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPayrateRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPayrateRepository)(nil).GetByID), ctx, id)
}

// GetByProject mocks base method.
func (m *MockPayrateRepository) GetByProject(ctx context.Context, projectID uint) ([]*domain.Payrate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProject", ctx, projectID)
	ret0, _ := ret[0].([]*domain.Payrate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProject indicates an expected call of GetByProject.
func (mr *MockPayrateRepositoryMockRecorder) GetByProject(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProject", reflect.TypeOf((*MockPayrateRepository)(nil).GetByProject), ctx, projectID)
}

// GetCurrentOrUpcomingByProject mocks base method.
func (m *MockPayrateRepository) GetCurrentOrUpcomingByProject(ctx context.Context, projectID uint) (*domain.Payrate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentOrUpcomingByProject", ctx, projectID)
	ret0, _ := ret[0].(*domain.Payrate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentOrUpcomingByProject indicates an expected call of GetCurrentOrUpcomingByProject.
func (mr *MockPayrateRepositoryMockRecorder) GetCurrentOrUpcomingByProject(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentOrUpcomingByProject", reflect.TypeOf((*MockPayrateRepository)(nil).GetCurrentOrUpcomingByProject), ctx, projectID)
}

// HasProjectTimesheetsFromDate mocks base method.
func (m *MockPayrateRepository) HasProjectTimesheetsFromDate(ctx context.Context, projectID uint, fromDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasProjectTimesheetsFromDate", ctx, projectID, fromDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasProjectTimesheetsFromDate indicates an expected call of HasProjectTimesheetsFromDate.
func (mr *MockPayrateRepositoryMockRecorder) HasProjectTimesheetsFromDate(ctx, projectID, fromDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasProjectTimesheetsFromDate", reflect.TypeOf((*MockPayrateRepository)(nil).HasProjectTimesheetsFromDate), ctx, projectID, fromDate)
}

// HasTimesheetsFromDate mocks base method.
func (m *MockPayrateRepository) HasTimesheetsFromDate(ctx context.Context, id uint, fromDate time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTimesheetsFromDate", ctx, id, fromDate)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasTimesheetsFromDate indicates an expected call of HasTimesheetsFromDate.
func (mr *MockPayrateRepositoryMockRecorder) HasTimesheetsFromDate(ctx, id, fromDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTimesheetsFromDate", reflect.TypeOf((*MockPayrateRepository)(nil).HasTimesheetsFromDate), ctx, id, fromDate)
}

// IsUsedByTimesheets mocks base method.
func (m *MockPayrateRepository) IsUsedByTimesheets(ctx context.Context, id uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUsedByTimesheets", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUsedByTimesheets indicates an expected call of IsUsedByTimesheets.
func (mr *MockPayrateRepositoryMockRecorder) IsUsedByTimesheets(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUsedByTimesheets", reflect.TypeOf((*MockPayrateRepository)(nil).IsUsedByTimesheets), ctx, id)
}

// List mocks base method.
func (m *MockPayrateRepository) List(ctx context.Context, filters domain.PayrateFilters) ([]*domain.Payrate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*domain.Payrate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPayrateRepositoryMockRecorder) List(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPayrateRepository)(nil).List), ctx, filters)
}

// Update mocks base method.
func (m *MockPayrateRepository) Update(ctx context.Context, payrate *domain.Payrate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, payrate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPayrateRepositoryMockRecorder) Update(ctx, payrate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPayrateRepository)(nil).Update), ctx, payrate)
}

// ValidateActiveCount mocks base method.
func (m *MockPayrateRepository) ValidateActiveCount(ctx context.Context, tx interface{}, projectID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateActiveCount", ctx, tx, projectID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateActiveCount indicates an expected call of ValidateActiveCount.
func (mr *MockPayrateRepositoryMockRecorder) ValidateActiveCount(ctx, tx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateActiveCount", reflect.TypeOf((*MockPayrateRepository)(nil).ValidateActiveCount), ctx, tx, projectID)
}

// ValidateDateOrdering mocks base method.
func (m *MockPayrateRepository) ValidateDateOrdering(ctx context.Context, tx interface{}, projectID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateDateOrdering", ctx, tx, projectID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateDateOrdering indicates an expected call of ValidateDateOrdering.
func (mr *MockPayrateRepositoryMockRecorder) ValidateDateOrdering(ctx, tx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateDateOrdering", reflect.TypeOf((*MockPayrateRepository)(nil).ValidateDateOrdering), ctx, tx, projectID)
}
