// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/timesheet.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "api-server/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTimesheetRepository is a mock of TimesheetRepository interface.
type MockTimesheetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTimesheetRepositoryMockRecorder
}

// MockTimesheetRepositoryMockRecorder is the mock recorder for MockTimesheetRepository.
type MockTimesheetRepositoryMockRecorder struct {
	mock *MockTimesheetRepository
}

// NewMockTimesheetRepository creates a new mock instance.
func NewMockTimesheetRepository(ctrl *gomock.Controller) *MockTimesheetRepository {
	mock := &MockTimesheetRepository{ctrl: ctrl}
	mock.recorder = &MockTimesheetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimesheetRepository) EXPECT() *MockTimesheetRepositoryMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockTimesheetRepository) Approve(ctx context.Context, id, approvedBy uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", ctx, id, approvedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockTimesheetRepositoryMockRecorder) Approve(ctx, id, approvedBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockTimesheetRepository)(nil).Approve), ctx, id, approvedBy)
}

// BatchUpdatePaymentStatusToFailed mocks base method.
func (m *MockTimesheetRepository) BatchUpdatePaymentStatusToFailed(ctx context.Context, tx interface{}, timesheetIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdatePaymentStatusToFailed", ctx, tx, timesheetIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdatePaymentStatusToFailed indicates an expected call of BatchUpdatePaymentStatusToFailed.
func (mr *MockTimesheetRepositoryMockRecorder) BatchUpdatePaymentStatusToFailed(ctx, tx, timesheetIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdatePaymentStatusToFailed", reflect.TypeOf((*MockTimesheetRepository)(nil).BatchUpdatePaymentStatusToFailed), ctx, tx, timesheetIDs)
}

// BulkApprove mocks base method.
func (m *MockTimesheetRepository) BulkApprove(ctx context.Context, ids []uint, approvedBy uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkApprove", ctx, ids, approvedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkApprove indicates an expected call of BulkApprove.
func (mr *MockTimesheetRepositoryMockRecorder) BulkApprove(ctx, ids, approvedBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkApprove", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkApprove), ctx, ids, approvedBy)
}

// BulkReject mocks base method.
func (m *MockTimesheetRepository) BulkReject(ctx context.Context, ids []uint, rejectionReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkReject", ctx, ids, rejectionReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkReject indicates an expected call of BulkReject.
func (mr *MockTimesheetRepositoryMockRecorder) BulkReject(ctx, ids, rejectionReason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkReject", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkReject), ctx, ids, rejectionReason)
}

// BulkCreate mocks base method.
func (m *MockTimesheetRepository) BulkCreate(ctx context.Context, timesheets []*domain.Timesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, timesheets)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockTimesheetRepositoryMockRecorder) BulkCreate(ctx, timesheets interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkCreate), ctx, timesheets)
}

// BulkUpdate mocks base method.
func (m *MockTimesheetRepository) BulkUpdate(ctx context.Context, timesheets []*domain.Timesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdate", ctx, timesheets)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdate indicates an expected call of BulkUpdate.
func (mr *MockTimesheetRepositoryMockRecorder) BulkUpdate(ctx, timesheets interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdate", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkUpdate), ctx, timesheets)
}

// BulkUpdatePaymentStatus mocks base method.
func (m *MockTimesheetRepository) BulkUpdatePaymentStatus(ctx context.Context, updates []domain.PaymentStatusUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdatePaymentStatus", ctx, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdatePaymentStatus indicates an expected call of BulkUpdatePaymentStatus.
func (mr *MockTimesheetRepositoryMockRecorder) BulkUpdatePaymentStatus(ctx, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdatePaymentStatus", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkUpdatePaymentStatus), ctx, updates)
}

// BulkUpdateRevenuePaid mocks base method.
func (m *MockTimesheetRepository) BulkUpdateRevenuePaid(ctx context.Context, timesheetIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateRevenuePaid", ctx, timesheetIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateRevenuePaid indicates an expected call of BulkUpdateRevenuePaid.
func (mr *MockTimesheetRepositoryMockRecorder) BulkUpdateRevenuePaid(ctx, timesheetIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateRevenuePaid", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkUpdateRevenuePaid), ctx, timesheetIDs)
}

// BulkUpdateRevenueReceivable mocks base method.
func (m *MockTimesheetRepository) BulkUpdateRevenueReceivable(ctx context.Context, updates map[uint]int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateRevenueReceivable", ctx, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateRevenueReceivable indicates an expected call of BulkUpdateRevenueReceivable.
func (mr *MockTimesheetRepositoryMockRecorder) BulkUpdateRevenueReceivable(ctx, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateRevenueReceivable", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkUpdateRevenueReceivable), ctx, updates)
}

// BulkUpdateTransactionID mocks base method.
func (m *MockTimesheetRepository) BulkUpdateTransactionID(ctx context.Context, transactionID uint, timesheetIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateTransactionID", ctx, transactionID, timesheetIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateTransactionID indicates an expected call of BulkUpdateTransactionID.
func (mr *MockTimesheetRepositoryMockRecorder) BulkUpdateTransactionID(ctx, transactionID, timesheetIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateTransactionID", reflect.TypeOf((*MockTimesheetRepository)(nil).BulkUpdateTransactionID), ctx, transactionID, timesheetIDs)
}

// Count mocks base method.
func (m *MockTimesheetRepository) Count(ctx context.Context, filters domain.TimesheetFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockTimesheetRepositoryMockRecorder) Count(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockTimesheetRepository)(nil).Count), ctx, filters)
}

// CountDistinctEmployees mocks base method.
func (m *MockTimesheetRepository) CountDistinctEmployees(ctx context.Context, filters domain.TimesheetFilters) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDistinctEmployees", ctx, filters)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDistinctEmployees indicates an expected call of CountDistinctEmployees.
func (mr *MockTimesheetRepositoryMockRecorder) CountDistinctEmployees(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDistinctEmployees", reflect.TypeOf((*MockTimesheetRepository)(nil).CountDistinctEmployees), ctx, filters)
}

// CountDistinctEmployeesPaidInPeriod mocks base method.
func (m *MockTimesheetRepository) CountDistinctEmployeesPaidInPeriod(ctx context.Context, startDate, endDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDistinctEmployeesPaidInPeriod", ctx, startDate, endDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDistinctEmployeesPaidInPeriod indicates an expected call of CountDistinctEmployeesPaidInPeriod.
func (mr *MockTimesheetRepositoryMockRecorder) CountDistinctEmployeesPaidInPeriod(ctx, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDistinctEmployeesPaidInPeriod", reflect.TypeOf((*MockTimesheetRepository)(nil).CountDistinctEmployeesPaidInPeriod), ctx, startDate, endDate)
}

// CountDistinctWorkingDays mocks base method.
func (m *MockTimesheetRepository) CountDistinctWorkingDays(ctx context.Context, employeeID, projectID uint, fromDate, toDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDistinctWorkingDays", ctx, employeeID, projectID, fromDate, toDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDistinctWorkingDays indicates an expected call of CountDistinctWorkingDays.
func (mr *MockTimesheetRepositoryMockRecorder) CountDistinctWorkingDays(ctx, employeeID, projectID, fromDate, toDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDistinctWorkingDays", reflect.TypeOf((*MockTimesheetRepository)(nil).CountDistinctWorkingDays), ctx, employeeID, projectID, fromDate, toDate)
}

// CountEmployeesPaidInLast30Days mocks base method.
func (m *MockTimesheetRepository) CountEmployeesPaidInLast30Days(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEmployeesPaidInLast30Days", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEmployeesPaidInLast30Days indicates an expected call of CountEmployeesPaidInLast30Days.
func (mr *MockTimesheetRepositoryMockRecorder) CountEmployeesPaidInLast30Days(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEmployeesPaidInLast30Days", reflect.TypeOf((*MockTimesheetRepository)(nil).CountEmployeesPaidInLast30Days), ctx)
}

// CountTimesheets mocks base method.
func (m *MockTimesheetRepository) CountTimesheets(ctx context.Context, projectID, employeeID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTimesheets", ctx, projectID, employeeID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTimesheets indicates an expected call of CountTimesheets.
func (mr *MockTimesheetRepositoryMockRecorder) CountTimesheets(ctx, projectID, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTimesheets", reflect.TypeOf((*MockTimesheetRepository)(nil).CountTimesheets), ctx, projectID, employeeID)
}

// CountTimesheetsByEmployeeID mocks base method.
func (m *MockTimesheetRepository) CountTimesheetsByEmployeeID(ctx context.Context, employeeID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTimesheetsByEmployeeID", ctx, employeeID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTimesheetsByEmployeeID indicates an expected call of CountTimesheetsByEmployeeID.
func (mr *MockTimesheetRepositoryMockRecorder) CountTimesheetsByEmployeeID(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTimesheetsByEmployeeID", reflect.TypeOf((*MockTimesheetRepository)(nil).CountTimesheetsByEmployeeID), ctx, employeeID)
}

// Create mocks base method.
func (m *MockTimesheetRepository) Create(ctx context.Context, timesheet *domain.Timesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, timesheet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTimesheetRepositoryMockRecorder) Create(ctx, timesheet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTimesheetRepository)(nil).Create), ctx, timesheet)
}

// Delete mocks base method.
func (m *MockTimesheetRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTimesheetRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTimesheetRepository)(nil).Delete), ctx, id)
}

// HardDelete mocks base method.
func (m *MockTimesheetRepository) HardDelete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockTimesheetRepositoryMockRecorder) HardDelete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockTimesheetRepository)(nil).HardDelete), ctx, id)
}

// DeleteByProjectID mocks base method.
func (m *MockTimesheetRepository) DeleteByProjectID(ctx context.Context, projectID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByProjectID", ctx, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByProjectID indicates an expected call of DeleteByProjectID.
func (mr *MockTimesheetRepositoryMockRecorder) DeleteByProjectID(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByProjectID", reflect.TypeOf((*MockTimesheetRepository)(nil).DeleteByProjectID), ctx, projectID)
}

// GetApprovedSalaryTotal mocks base method.
func (m *MockTimesheetRepository) GetApprovedSalaryTotal(ctx context.Context, startDate, endDate time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApprovedSalaryTotal", ctx, startDate, endDate)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApprovedSalaryTotal indicates an expected call of GetApprovedSalaryTotal.
func (mr *MockTimesheetRepositoryMockRecorder) GetApprovedSalaryTotal(ctx, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApprovedSalaryTotal", reflect.TypeOf((*MockTimesheetRepository)(nil).GetApprovedSalaryTotal), ctx, startDate, endDate)
}

// GetByEmployee mocks base method.
func (m *MockTimesheetRepository) GetByEmployee(ctx context.Context, employeeID uint, fromDate, toDate time.Time) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmployee", ctx, employeeID, fromDate, toDate)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmployee indicates an expected call of GetByEmployee.
func (mr *MockTimesheetRepositoryMockRecorder) GetByEmployee(ctx, employeeID, fromDate, toDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmployee", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByEmployee), ctx, employeeID, fromDate, toDate)
}

// GetByEmployeeAndPeriod mocks base method.
func (m *MockTimesheetRepository) GetByEmployeeAndPeriod(ctx context.Context, employeeID uint, fromDate, toDate time.Time) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmployeeAndPeriod", ctx, employeeID, fromDate, toDate)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmployeeAndPeriod indicates an expected call of GetByEmployeeAndPeriod.
func (mr *MockTimesheetRepositoryMockRecorder) GetByEmployeeAndPeriod(ctx, employeeID, fromDate, toDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmployeeAndPeriod", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByEmployeeAndPeriod), ctx, employeeID, fromDate, toDate)
}

// GetByEmployeeDateCombos mocks base method.
func (m *MockTimesheetRepository) GetByEmployeeDateCombos(ctx context.Context, combos []domain.EmployeeDateCombo) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmployeeDateCombos", ctx, combos)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmployeeDateCombos indicates an expected call of GetByEmployeeDateCombos.
func (mr *MockTimesheetRepositoryMockRecorder) GetByEmployeeDateCombos(ctx, combos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmployeeDateCombos", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByEmployeeDateCombos), ctx, combos)
}

// GetByID mocks base method.
func (m *MockTimesheetRepository) GetByID(ctx context.Context, id uint) (*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTimesheetRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockTimesheetRepository) GetByIDs(ctx context.Context, ids []uint) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockTimesheetRepositoryMockRecorder) GetByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByIDs), ctx, ids)
}

// GetByTransactionID mocks base method.
func (m *MockTimesheetRepository) GetByTransactionID(ctx context.Context, transactionID uint) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTransactionID indicates an expected call of GetByTransactionID.
func (mr *MockTimesheetRepositoryMockRecorder) GetByTransactionID(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTransactionID", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByTransactionID), ctx, transactionID)
}

// GetByIDsWithoutRelations mocks base method.
func (m *MockTimesheetRepository) GetByIDsWithoutRelations(ctx context.Context, ids []uint) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDsWithoutRelations", ctx, ids)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDsWithoutRelations indicates an expected call of GetByIDsWithoutRelations.
func (mr *MockTimesheetRepositoryMockRecorder) GetByIDsWithoutRelations(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDsWithoutRelations", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByIDsWithoutRelations), ctx, ids)
}

// GetTimesheetDatesByIDs mocks base method.
func (m *MockTimesheetRepository) GetTimesheetDatesByIDs(ctx context.Context, ids []uint) (map[uint]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimesheetDatesByIDs", ctx, ids)
	ret0, _ := ret[0].(map[uint]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimesheetDatesByIDs indicates an expected call of GetTimesheetDatesByIDs.
func (mr *MockTimesheetRepositoryMockRecorder) GetTimesheetDatesByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimesheetDatesByIDs", reflect.TypeOf((*MockTimesheetRepository)(nil).GetTimesheetDatesByIDs), ctx, ids)
}

// GetByProject mocks base method.
func (m *MockTimesheetRepository) GetByProject(ctx context.Context, projectID uint, fromDate, toDate time.Time) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProject", ctx, projectID, fromDate, toDate)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProject indicates an expected call of GetByProject.
func (mr *MockTimesheetRepositoryMockRecorder) GetByProject(ctx, projectID, fromDate, toDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProject", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByProject), ctx, projectID, fromDate, toDate)
}

// GetByProjectAndEmployee mocks base method.
func (m *MockTimesheetRepository) GetByProjectAndEmployee(ctx context.Context, projectID, employeeID uint, fromDate, toDate time.Time) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectAndEmployee", ctx, projectID, employeeID, fromDate, toDate)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectAndEmployee indicates an expected call of GetByProjectAndEmployee.
func (mr *MockTimesheetRepositoryMockRecorder) GetByProjectAndEmployee(ctx, projectID, employeeID, fromDate, toDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectAndEmployee", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByProjectAndEmployee), ctx, projectID, employeeID, fromDate, toDate)
}

// GetByProjectEmployeeDate mocks base method.
func (m *MockTimesheetRepository) GetByProjectEmployeeDate(ctx context.Context, projectID, employeeID uint, date time.Time) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectEmployeeDate", ctx, projectID, employeeID, date)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectEmployeeDate indicates an expected call of GetByProjectEmployeeDate.
func (mr *MockTimesheetRepositoryMockRecorder) GetByProjectEmployeeDate(ctx, projectID, employeeID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectEmployeeDate", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByProjectEmployeeDate), ctx, projectID, employeeID, date)
}

// GetByProjectEmployeeDateHourType mocks base method.
func (m *MockTimesheetRepository) GetByProjectEmployeeDateHourType(ctx context.Context, projectID, employeeID uint, date time.Time, hourType string) (*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectEmployeeDateHourType", ctx, projectID, employeeID, date, hourType)
	ret0, _ := ret[0].(*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectEmployeeDateHourType indicates an expected call of GetByProjectEmployeeDateHourType.
func (mr *MockTimesheetRepositoryMockRecorder) GetByProjectEmployeeDateHourType(ctx, projectID, employeeID, date, hourType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectEmployeeDateHourType", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByProjectEmployeeDateHourType), ctx, projectID, employeeID, date, hourType)
}

// GetByProjectEmployeeDatePaytype mocks base method.
func (m *MockTimesheetRepository) GetByProjectEmployeeDatePaytype(ctx context.Context, projectID, employeeID uint, date time.Time, paytype string) (*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectEmployeeDatePaytype", ctx, projectID, employeeID, date, paytype)
	ret0, _ := ret[0].(*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectEmployeeDatePaytype indicates an expected call of GetByProjectEmployeeDatePaytype.
func (mr *MockTimesheetRepositoryMockRecorder) GetByProjectEmployeeDatePaytype(ctx, projectID, employeeID, date, paytype interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectEmployeeDatePaytype", reflect.TypeOf((*MockTimesheetRepository)(nil).GetByProjectEmployeeDatePaytype), ctx, projectID, employeeID, date, paytype)
}

// GetEmployeeCurrentWeekHours mocks base method.
func (m *MockTimesheetRepository) GetEmployeeCurrentWeekHours(ctx context.Context, employeeID uint) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeCurrentWeekHours", ctx, employeeID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeCurrentWeekHours indicates an expected call of GetEmployeeCurrentWeekHours.
func (mr *MockTimesheetRepositoryMockRecorder) GetEmployeeCurrentWeekHours(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeCurrentWeekHours", reflect.TypeOf((*MockTimesheetRepository)(nil).GetEmployeeCurrentWeekHours), ctx, employeeID)
}

// GetEmployeeMonthlyPayrollSummary mocks base method.
func (m *MockTimesheetRepository) GetEmployeeMonthlyPayrollSummary(ctx context.Context, employeeID uint) (*domain.PayrollSummaryAggregated, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeMonthlyPayrollSummary", ctx, employeeID)
	ret0, _ := ret[0].(*domain.PayrollSummaryAggregated)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeMonthlyPayrollSummary indicates an expected call of GetEmployeeMonthlyPayrollSummary.
func (mr *MockTimesheetRepositoryMockRecorder) GetEmployeeMonthlyPayrollSummary(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeMonthlyPayrollSummary", reflect.TypeOf((*MockTimesheetRepository)(nil).GetEmployeeMonthlyPayrollSummary), ctx, employeeID)
}

// GetEmployeeTimesheetSummaryAggregated mocks base method.
func (m *MockTimesheetRepository) GetEmployeeTimesheetSummaryAggregated(ctx context.Context, employeeID uint) (*domain.TimesheetSummaryAggregated, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeTimesheetSummaryAggregated", ctx, employeeID)
	ret0, _ := ret[0].(*domain.TimesheetSummaryAggregated)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeTimesheetSummaryAggregated indicates an expected call of GetEmployeeTimesheetSummaryAggregated.
func (mr *MockTimesheetRepositoryMockRecorder) GetEmployeeTimesheetSummaryAggregated(ctx, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeTimesheetSummaryAggregated", reflect.TypeOf((*MockTimesheetRepository)(nil).GetEmployeeTimesheetSummaryAggregated), ctx, employeeID)
}

// GetEntryTableData mocks base method.
func (m *MockTimesheetRepository) GetEntryTableData(ctx context.Context, projectID uint, employeeIDs []uint, fromDate, toDate time.Time) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntryTableData", ctx, projectID, employeeIDs, fromDate, toDate)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntryTableData indicates an expected call of GetEntryTableData.
func (mr *MockTimesheetRepositoryMockRecorder) GetEntryTableData(ctx, projectID, employeeIDs, fromDate, toDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntryTableData", reflect.TypeOf((*MockTimesheetRepository)(nil).GetEntryTableData), ctx, projectID, employeeIDs, fromDate, toDate)
}

// GetFirstPaidTimesheetDate mocks base method.
func (m *MockTimesheetRepository) GetFirstPaidTimesheetDate(ctx context.Context) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstPaidTimesheetDate", ctx)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstPaidTimesheetDate indicates an expected call of GetFirstPaidTimesheetDate.
func (mr *MockTimesheetRepositoryMockRecorder) GetFirstPaidTimesheetDate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstPaidTimesheetDate", reflect.TypeOf((*MockTimesheetRepository)(nil).GetFirstPaidTimesheetDate), ctx)
}

// GetLatestTimesheetDate mocks base method.
func (m *MockTimesheetRepository) GetLatestTimesheetDate(ctx context.Context, projectID, employeeID uint) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestTimesheetDate", ctx, projectID, employeeID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestTimesheetDate indicates an expected call of GetLatestTimesheetDate.
func (mr *MockTimesheetRepositoryMockRecorder) GetLatestTimesheetDate(ctx, projectID, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestTimesheetDate", reflect.TypeOf((*MockTimesheetRepository)(nil).GetLatestTimesheetDate), ctx, projectID, employeeID)
}

// GetPaidSalaryByEmployee mocks base method.
func (m *MockTimesheetRepository) GetPaidSalaryByEmployee(ctx context.Context, startDate, endDate time.Time) (map[uint]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaidSalaryByEmployee", ctx, startDate, endDate)
	ret0, _ := ret[0].(map[uint]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaidSalaryByEmployee indicates an expected call of GetPaidSalaryByEmployee.
func (mr *MockTimesheetRepositoryMockRecorder) GetPaidSalaryByEmployee(ctx, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaidSalaryByEmployee", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPaidSalaryByEmployee), ctx, startDate, endDate)
}

// GetPaidSalaryForMonth mocks base method.
func (m *MockTimesheetRepository) GetPaidSalaryForMonth(ctx context.Context, startDate, endDate time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaidSalaryForMonth", ctx, startDate, endDate)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaidSalaryForMonth indicates an expected call of GetPaidSalaryForMonth.
func (mr *MockTimesheetRepositoryMockRecorder) GetPaidSalaryForMonth(ctx, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaidSalaryForMonth", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPaidSalaryForMonth), ctx, startDate, endDate)
}

// GetPaidTimesheetsInDateRange mocks base method.
func (m *MockTimesheetRepository) GetPaidTimesheetsInDateRange(ctx context.Context, startDate, endDate time.Time, timesheets *[]*domain.Timesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaidTimesheetsInDateRange", ctx, startDate, endDate, timesheets)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPaidTimesheetsInDateRange indicates an expected call of GetPaidTimesheetsInDateRange.
func (mr *MockTimesheetRepositoryMockRecorder) GetPaidTimesheetsInDateRange(ctx, startDate, endDate, timesheets interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaidTimesheetsInDateRange", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPaidTimesheetsInDateRange), ctx, startDate, endDate, timesheets)
}

// GetPaymentHistories mocks base method.
func (m *MockTimesheetRepository) GetPaymentHistories(ctx context.Context, filters domain.PaymentHistoryFilters) ([]*domain.PaymentHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentHistories", ctx, filters)
	ret0, _ := ret[0].([]*domain.PaymentHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPaymentHistories indicates an expected call of GetPaymentHistories.
func (mr *MockTimesheetRepositoryMockRecorder) GetPaymentHistories(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentHistories", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPaymentHistories), ctx, filters)
}

// GetPendingApprovalCount mocks base method.
func (m *MockTimesheetRepository) GetPendingApprovalCount(ctx context.Context, startDate, endDate time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingApprovalCount", ctx, startDate, endDate)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingApprovalCount indicates an expected call of GetPendingApprovalCount.
func (mr *MockTimesheetRepositoryMockRecorder) GetPendingApprovalCount(ctx, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingApprovalCount", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPendingApprovalCount), ctx, startDate, endDate)
}

// GetPendingSalaryForMonth mocks base method.
func (m *MockTimesheetRepository) GetPendingSalaryForMonth(ctx context.Context, startDate, endDate time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingSalaryForMonth", ctx, startDate, endDate)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingSalaryForMonth indicates an expected call of GetPendingSalaryForMonth.
func (mr *MockTimesheetRepositoryMockRecorder) GetPendingSalaryForMonth(ctx, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingSalaryForMonth", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPendingSalaryForMonth), ctx, startDate, endDate)
}

// GetPendingSalaryForMonthBySchedule mocks base method.
func (m *MockTimesheetRepository) GetPendingSalaryForMonthBySchedule(ctx context.Context, startDate, endDate time.Time, schedule domain.PaymentSchedule) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingSalaryForMonthBySchedule", ctx, startDate, endDate, schedule)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingSalaryForMonthBySchedule indicates an expected call of GetPendingSalaryForMonthBySchedule.
func (mr *MockTimesheetRepositoryMockRecorder) GetPendingSalaryForMonthBySchedule(ctx, startDate, endDate, schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingSalaryForMonthBySchedule", reflect.TypeOf((*MockTimesheetRepository)(nil).GetPendingSalaryForMonthBySchedule), ctx, startDate, endDate, schedule)
}

// GetProjectsForEmployeeOnDate mocks base method.
func (m *MockTimesheetRepository) GetProjectsForEmployeeOnDate(ctx context.Context, employeeID uint, date time.Time) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectsForEmployeeOnDate", ctx, employeeID, date)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectsForEmployeeOnDate indicates an expected call of GetProjectsForEmployeeOnDate.
func (mr *MockTimesheetRepositoryMockRecorder) GetProjectsForEmployeeOnDate(ctx, employeeID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectsForEmployeeOnDate", reflect.TypeOf((*MockTimesheetRepository)(nil).GetProjectsForEmployeeOnDate), ctx, employeeID, date)
}

// GetSummaryByProject mocks base method.
func (m *MockTimesheetRepository) GetSummaryByProject(ctx context.Context, projectID uint, fromDate, toDate time.Time) (*domain.TimesheetSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummaryByProject", ctx, projectID, fromDate, toDate)
	ret0, _ := ret[0].(*domain.TimesheetSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummaryByProject indicates an expected call of GetSummaryByProject.
func (mr *MockTimesheetRepositoryMockRecorder) GetSummaryByProject(ctx, projectID, fromDate, toDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummaryByProject", reflect.TypeOf((*MockTimesheetRepository)(nil).GetSummaryByProject), ctx, projectID, fromDate, toDate)
}

// GetSummaryStats mocks base method.
func (m *MockTimesheetRepository) GetSummaryStats(ctx context.Context, filters domain.TimesheetFilters) (*domain.TimesheetSummaryStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummaryStats", ctx, filters)
	ret0, _ := ret[0].(*domain.TimesheetSummaryStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummaryStats indicates an expected call of GetSummaryStats.
func (mr *MockTimesheetRepositoryMockRecorder) GetSummaryStats(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummaryStats", reflect.TypeOf((*MockTimesheetRepository)(nil).GetSummaryStats), ctx, filters)
}

// GetAccrualCohort mocks base method.
func (m *MockTimesheetRepository) GetAccrualCohort(ctx context.Context, filters domain.TimesheetFilters) ([]domain.TimesheetAccrualDailyRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccrualCohort", ctx, filters)
	ret0, _ := ret[0].([]domain.TimesheetAccrualDailyRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccrualCohort indicates an expected call of GetAccrualCohort.
func (mr *MockTimesheetRepositoryMockRecorder) GetAccrualCohort(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccrualCohort", reflect.TypeOf((*MockTimesheetRepository)(nil).GetAccrualCohort), ctx, filters)
}

// GetTotalPaidSalary mocks base method.
func (m *MockTimesheetRepository) GetTotalPaidSalary(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalPaidSalary", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalPaidSalary indicates an expected call of GetTotalPaidSalary.
func (mr *MockTimesheetRepositoryMockRecorder) GetTotalPaidSalary(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalPaidSalary", reflect.TypeOf((*MockTimesheetRepository)(nil).GetTotalPaidSalary), ctx)
}

// HasNonEditableTimesheetsAfterDate mocks base method.
func (m *MockTimesheetRepository) HasNonEditableTimesheetsAfterDate(ctx context.Context, projectID, employeeID uint, date time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasNonEditableTimesheetsAfterDate", ctx, projectID, employeeID, date)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasNonEditableTimesheetsAfterDate indicates an expected call of HasNonEditableTimesheetsAfterDate.
func (mr *MockTimesheetRepositoryMockRecorder) HasNonEditableTimesheetsAfterDate(ctx, projectID, employeeID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNonEditableTimesheetsAfterDate", reflect.TypeOf((*MockTimesheetRepository)(nil).HasNonEditableTimesheetsAfterDate), ctx, projectID, employeeID, date)
}

// HasTimesheetsAfterDate mocks base method.
func (m *MockTimesheetRepository) HasTimesheetsAfterDate(ctx context.Context, projectID, employeeID uint, date time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTimesheetsAfterDate", ctx, projectID, employeeID, date)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasTimesheetsAfterDate indicates an expected call of HasTimesheetsAfterDate.
func (mr *MockTimesheetRepositoryMockRecorder) HasTimesheetsAfterDate(ctx, projectID, employeeID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTimesheetsAfterDate", reflect.TypeOf((*MockTimesheetRepository)(nil).HasTimesheetsAfterDate), ctx, projectID, employeeID, date)
}

// HasTimesheetsForAssignment mocks base method.
func (m *MockTimesheetRepository) HasTimesheetsForAssignment(ctx context.Context, projectID, employeeID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTimesheetsForAssignment", ctx, projectID, employeeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasTimesheetsForAssignment indicates an expected call of HasTimesheetsForAssignment.
func (mr *MockTimesheetRepositoryMockRecorder) HasTimesheetsForAssignment(ctx, projectID, employeeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTimesheetsForAssignment", reflect.TypeOf((*MockTimesheetRepository)(nil).HasTimesheetsForAssignment), ctx, projectID, employeeID)
}

// List mocks base method.
func (m *MockTimesheetRepository) List(ctx context.Context, filters domain.TimesheetFilters) ([]*domain.Timesheet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*domain.Timesheet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTimesheetRepositoryMockRecorder) List(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTimesheetRepository)(nil).List), ctx, filters)
}

// ListGroupedByEmployee mocks base method.
func (m *MockTimesheetRepository) ListGroupedByEmployee(ctx context.Context, filters domain.TimesheetFilters) ([]domain.EmployeeGroupResult, []*domain.Timesheet, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupedByEmployee", ctx, filters)
	ret0, _ := ret[0].([]domain.EmployeeGroupResult)
	ret1, _ := ret[1].([]*domain.Timesheet)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListGroupedByEmployee indicates an expected call of ListGroupedByEmployee.
func (mr *MockTimesheetRepositoryMockRecorder) ListGroupedByEmployee(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupedByEmployee", reflect.TypeOf((*MockTimesheetRepository)(nil).ListGroupedByEmployee), ctx, filters)
}

// Reject mocks base method.
func (m *MockTimesheetRepository) Reject(ctx context.Context, id uint, rejectionReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx, id, rejectionReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reject indicates an expected call of Reject.
func (mr *MockTimesheetRepositoryMockRecorder) Reject(ctx, id, rejectionReason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockTimesheetRepository)(nil).Reject), ctx, id, rejectionReason)
}

// Reset mocks base method.
func (m *MockTimesheetRepository) Reset(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockTimesheetRepositoryMockRecorder) Reset(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockTimesheetRepository)(nil).Reset), ctx, id)
}

// SetForcePayroll mocks base method.
func (m *MockTimesheetRepository) SetForcePayroll(ctx context.Context, id uint, flag bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetForcePayroll", ctx, id, flag)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetForcePayroll indicates an expected call of SetForcePayroll.
func (mr *MockTimesheetRepositoryMockRecorder) SetForcePayroll(ctx, id, flag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetForcePayroll", reflect.TypeOf((*MockTimesheetRepository)(nil).SetForcePayroll), ctx, id, flag)
}

// Update mocks base method.
func (m *MockTimesheetRepository) Update(ctx context.Context, timesheet *domain.Timesheet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, timesheet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTimesheetRepositoryMockRecorder) Update(ctx, timesheet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTimesheetRepository)(nil).Update), ctx, timesheet)
}

// CountUnsettledPaidTimesheets mocks base method.
func (m *MockTimesheetRepository) CountUnsettledPaidTimesheets(ctx context.Context, projectID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnsettledPaidTimesheets", ctx, projectID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnsettledPaidTimesheets indicates an expected call of CountUnsettledPaidTimesheets.
func (mr *MockTimesheetRepositoryMockRecorder) CountUnsettledPaidTimesheets(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnsettledPaidTimesheets", reflect.TypeOf((*MockTimesheetRepository)(nil).CountUnsettledPaidTimesheets), ctx, projectID)
}
